### ISSUE TITLE
Support Spotify playlist folder structure

### ISSUE THREAD

**Issue by vdbee** [dirkgroenen/mopidy-mopify#10]
Hi, thanks for the impressive update! However, I really liked the way you implemented the playlist folders in the previous version. Is there any chance to have the folders in the left panel underneath "playlists" and that clicking a folder filters the playlists in the right-most panel?

**Comment by dirkgroenen** [comment]
Thanks! I've been thinking about different ways to implement the folder structure, but couldn't come up with one that was 'good' enough.

Your idea may work, I will try it. In the mean time I would love to hear other ideas to implement the folder structure.

**Comment by jaedb** [comment]
I agree with `vdbee`, I use the left-hand playlists to receive drag-and-drop for tracks to be added to the playlist. It does become quite greedy of screen real-estate though.

What if it was treated like the Contacts/Hangouts/Phone call panels in Gmail (far bottom left)? Collapsible if you're not using it, sticky revealed if you are.

**Comment by dirkgroenen** [comment]
I'm indeed a bit afraid that there isn't enough space for the playlist directories. I will play around with your idea @jaedb, thanks.

**Comment by dirkgroenen** [comment]
Just added this playlist feature in v1.1.0. I've added a one-level-depth directory browsing in the left menu. Please check it out and let me know if this works for you. I'm working on a full-hd monitor, so everything works fine for me, but I can understand that this doesn't work for some people. 

Please note that directory browsing is only available for playlists coming from Mopidy. The spotify service now has an extra settings page where you can enable or disable the Spotify source.

**Comment by vdbee** [comment]
Tried it quickly but it works like a charm! No difficulties here on a 7 inch tablet as well

**Comment by kingosticks** [comment]
Really nice solution but I'm hitting the limitation of one-level-depth. It's a bit of a funny one which has come up before but my playlist called 'Lost Forever // Lost Together' and when selected it's empty. Maybe it's too hacky but could you identify seemingly empty levels of hierarchy as actually being flat?

![screenshot]
(http://s14.postimg.org/wz3ftwsb5/Screenshot_050115_14_42_47.png)

**Comment by dirkgroenen** [comment]
Ah, the 'mopidy directory indicator problem'. I will make a directory with your name and check how the code reacts on it and how to avoid it.

I'm using multiple depth directories my own so I do want to extend the current code to handle this in the future. It's at the moment mostly a UI/UX problem since I'm not sure how I want the folders to be displayed. I'm thinking about a normal finder idea where folders are located in the playlist overview. Let me know if you

**Comment by dirkgroenen** [comment]
... or others have some ideas on how to display the folders. 

(Can't edit the comment since I'm on my phone at the moment, so finishing my sentence with this comment)
