### ISSUE TITLE
Cannot save albums anymore

### ISSUE THREAD

**Issue by syntelman** [dirkgroenen/mopidy-mopify#104]
Hi!
I am the only one who has the problems that I cannot add/save albums to my collection anymore? Nothing happens at all when I press "SAVE ALBUM". Neither in Chrome of Firefox. Cheers!

**Comment by dirkgroenen** [comment]
Hmm I see. I'm also not being able to save an album anymore. I will check it out!

**Comment by dirkgroenen** [comment]
Fixed in 1.5.1 which I've just released
