### ISSUE TITLE
iPhone WebApp 

### ISSUE THREAD

**Issue by joenas** [dirkgroenen/mopidy-mopify#106]
Hi and thanks for an awesome client!

I couldn't find an issue about this but it would be nice to add `<meta content="yes" name="apple-mobile-web-app-capable">` to [index.html](https://github.com/dirkgroenen/mopidy-mopify/blob/master/src/index.html) for iPhone WebApp!

**Comment by dirkgroenen** [comment]
Related to Issue #98, I will mark that one for the next milestone and close this one.
