### ISSUE TITLE
[new radio] Results overlapped by UI

### ISSUE THREAD

**Issue by Chronophobe** [dirkgroenen/mopidy-mopify#107]
When searching for artists/albums to create a new station the results are partially overlapped by the UI below (the white area where recently played stations show up).

![New station results overlap](http://i.imgur.com/ZaedCrN.png)

Edit: this is in Firefox 38.0.5 on Arch Linux.

**Comment by dirkgroenen** [comment]
Just checked it and can confirm that this also happens in Chrome (in combination with Arch Linux). Will check it out.

**Comment by dirkgroenen** [comment]
Fixed in latest version.
