### ISSUE TITLE
Add mopidy-podcast support

### ISSUE THREAD

**Issue by Kantraz** [dirkgroenen/mopidy-mopify#109]
I love this webui so much, it is the most elegant by far. Something I miss using Mopify though, is the ability to play podcasts.
I know the main focus of this project is to resemble the spotify experience, but I think that podcast support would be a nice extra touch.

It doesn't have to be a big part of the ui, just the option to browse subsribed podcasts and perhaps  mopidy-podcast-itunes support.

**Comment by dirkgroenen** [comment]
I still want to add more services to Mopify, but I'm really struggling with how to bring that into the interface. Until I, or someone else, have a good idea on how to merge those services it won't be part of the interface. 

Let me know if you know something or have an idea. I would love to see Mopify grow and have support for more services so it becomes the 'main interface' for mopidy.

**Comment by Kantraz** [comment]
As for podcast, a link in the Your Music section would be fine, and then present those you've subscribed to, in the same way as albums or artists? :)

**Comment by dirkgroenen** [comment]
That might be a good solution. Let me think about it! I'll let you know when I'm going to work on it.

**Comment by dirkgroenen** [comment]
I've opened a new issue which will be the new discussion point for Mopify 2.0 and it's extra services. #113
