### ISSUE TITLE
Quick access menu for search

### ISSUE THREAD

**Issue by vdbee** [dirkgroenen/mopidy-mopify#11]
Hi again..

One more question: Is it possible to incorporate the small list that appeared underneath the search-box in the older version? It allows quick reviewing of the search results without scrolling. I found it very effective.

Do not misunderstand me: I really like your work, thanks!

**Comment by dirkgroenen** [comment]
Indeed some of the features that were present in the old Mopify didn't get along. I'll keep this issue opened as an enhancement, but I don't know when I'm going to implement it.

Please keep posting your opinion and missing things so I can make it a better product.

**Comment by dirkgroenen** [comment]
Will be further discussed in #18
