### ISSUE TITLE
Infer ws port number/remove hardcoded port number

### ISSUE THREAD

**Issue by eudes** [dirkgroenen/mopidy-mopify#110]
I've been trying to configure Mopify behind nginx (on 192.168.X.X:80), while setting Mopidy's http address to localhost. Mopify tries to connect to Mopidy's HTTP API websocket via the external IP and the hardcoded port number, which is not where nginx is receiving and forwarding requests. It should be connecting to the address and port where the responses come from. E.g.: If responses are coming from 192.168.X.X:80, requests should go to ws:192.168.X.X:80, not 192.168.X.X:6680. This also happens if you change Mopidy's default http port (without nginx).
I know there's a manual setting for this, but it does not seem optimal. The default address and port number should not be hardcoded, but inferred from requests or responses.

**Comment by dirkgroenen** [comment]
I'm not really sure if I understand your problem. I've had Mopidy behind a proxy in our office and everything worked fine. 

You want that request from (for example) ``192.168.1.2:6680`` go to ``192.168.1.2:6680``?

**Comment by qurben** [comment]
I second this, I would like to change the default port for the web-socket connection to 80. Instead of having to change this setting in any client I use.

I monkey-patched this in my installation, but maybe there could be a way to set this in the settings?

**Comment by dirkgroenen** [comment]
Ah so If I understand you guys correctly you would like to see something like this:

- User goes to `http://192.168.1.5:6680` and Mopify sets it default port to `6680`
- User goes to `http://192.168.1.5:8000` and Mopify uses `8000` as its default port.

**Comment by qurben** [comment]
Yes, just use the same port as the application. I don't see a use-case where the websockets and the http are on a different port as they come from the same server anyway.

If the user were to set the 'Mopidy IP address' option they could also just add a port there.

Then you'll get:
```javascript
if (settings.ip)
  url = "ws://" + settings.ip + "/mopidy/ws";
else
  url = "ws://" + location.host + ":" + location.port "/mopidy/ws";
```
Maybe also check if the user has https enabled, and then use `wss://`

**Comment by schinken** [comment]
Anything new about this issue or about milestone 2.0.0?

**Comment by dirkgroenen** [comment]
I've just added this in the development branch and moved the release to 1.5.9.

**Comment by schinken** [comment]
Perfect! Thank you very much! :+1:

**Comment by AlexC** [comment]
@dirkgroenen Thanks for the fix, however it's not a full fix since calls to "mopify/queuemanager" are still going to the hard-coded port 6680. Seems there are many places where this happens, see https://github.com/dirkgroenen/mopidy-mopify/search?utf8=%E2%9C%93&q=6680

**Comment by dirkgroenen** [comment]
Ah I see, forgot about those. Just replaced them in the dev branch.

**Comment by dirkgroenen** [comment]
And live in 1.5.11...
