### ISSUE TITLE
Collaborative spotify playlists

### ISSUE THREAD

**Issue by npull** [dirkgroenen/mopidy-mopify#111]
Collaborative playlists don't seem to show up when you have "Use Spotify as playlist source" on. Love this feature otherwise, because it's so much faster than to let mopidy fetch the playlists. Another idea for improvement is to add sub-directories for the spotify playlists, it can be a bit hard sometimes to find the correct playlist when they are all in one big mess. And again, when you let mopidy fetch the playlists the sub-directories works fine.

**Comment by dirkgroenen** [comment]
Yes, I'm aware of this. It looks like Spotify doesn't return collaborative playlists, so there's not much I can do about it.

Same for the directories. The API doesn't return directories at this moment, so we have to wait until Spotify updates their API

**Comment by npull** [comment]
Alright, good to know. Thanks for the explanation.
