### ISSUE TITLE
Pressing the play button on an album or artist using Chrome, doesn't start the music.

### ISSUE THREAD

**Issue by neeohw** [dirkgroenen/mopidy-mopify#112]
When I click play on an artist or album (on the image), the music doesn't start playing. It works using Firefox, but not using Chrome.
I have to open the album and double click the first song.

**Comment by dirkgroenen** [comment]
Which version are you using and does the Developer Console show any errors?

**Comment by neeohw** [comment]
I was using 1.5.1, but now I've updated to 1.5.4 and it seems to work ...

I won't mind if you consider this bug fixed.
If I bump into this problem again, I'll remember to add the dev console log.



2015-07-12 17:46 GMT+02:00 Dirk Groenen <notifications@github.com>:

**Comment by dirkgroenen** [comment]
Allright, let's do that.
