### ISSUE TITLE
[V2.0] Add extra music sources

### ISSUE THREAD

**Issue by dirkgroenen** [dirkgroenen/mopidy-mopify#113]
Let's start summing (and maybe voting) some extra Mopidy music sources, since adding extra features is still the most requested feature.

At this point I'm still thinking about the way to implement this, since I don't want the music from other sources to mess with for example the search results. Mopify's core target is still providing a music client which descent feedback and a good UI/UX. 

A list with sources I'm planning to implement for now:
- [x] [Mopidy-Spotify](https://github.com/mopidy/mopidy-spotify)
- [ ] [Mopidy-Stream / Radio](https://docs.mopidy.com/en/latest/ext/stream/)
- [x] [Mopidy-SoundCloud](https://github.com/mopidy/mopidy-soundcloud)
- [x] [Local music](https://docs.mopidy.com/en/latest/ext/local/) (including the possibility to upload them via Mopify)
- [ ] [Mopidy-Podcast](https://github.com/tkem/mopidy-podcast)
- [ ] Overwrite/Create a better search extension which uses some sort of relevancy for returning correct tracks. (?)

Let me know if you have any extra service you would like to see, or if you have some ideas about how to integrate this into the current interface.

**Comment by chookies** [comment]
I vote +1 for local music. I like the direction you are going with Mopify and I love the sleek UI.
I'd be happy to contribute if you can point me in the right direction.

Maybe the same approach as the Spotify client can be taken with local files here. That is, take precedence for music from local sources over Spotify music. As for the other services, maybe search could group the results in a smart way, so the user knows from which source the music is retrieved. The search window now has Artists, Albums, Playlists, Tracks for groups, we could add Radio/Streams.

Of course, more groups means more space needed to show them. To solve that, users might be able to configure which results are shown first. So if you listen to podcasts a lot, you can move that group up and it will show first in the results.

Just brainstormin' here

**Comment by dirkgroenen** [comment]
I've already started on devving the backend for Local Music. At the moment there's a branch which already contains the code for uploading and managing songs through the Mopify client. After that's finished I will start thinking about a way to integrate it in the search results and library. 

I like your idea about creating more sort-able columns in the search results page. I was already planning on adding an extra column or place of information to each track which tells you the source, maybe in the context menu or something... 

As you can see, and probably noticed, there are a ton of options and making the right one is kinda hard at the moment. I don't want to make a decision now and get regrets from it later, when implementing more services. 

Let me know if you have more ideas. Just drop them in here, even if it's a big change or something really unrelated but still related ;) Everything helps!

**Comment by chookies** [comment]
Thinking about it, if you use the search bar, it's because you want to search for music, not for sources or music within sources per se. Adding the sources to the search window might lead to a lot of clutter in the search window, which would be bad for the UX. Listening music remains the main goal of the client. 

Considering that multiple sources contain duplicates of certain titles, we don't want to have duplicate search results. So maybe a user should be able to set his preference in which order sources are used, e.g.:
1. Local
2. Spotify
3. Soundcloud 
This way, the client can intelligently pick the right source for the user, instead of the user being bothered with choosing a source every search query.

Of course, podcasts and radio may still be a separate group/category next to albums, artists etc.

**Comment by dirkgroenen** [comment]
Yes I was thinking about that last night in bed. Might want to create an extra Search service which creates an `relevance` number based on some properties like: 

- Preferred service order  (Spotify, Local, Soundcloud)
- Returned order from Mopidy
- Word match (?)

I've never done something with search relevancy formulas before so I definitely need to take a sneak peak in some other libs. 

I think Podcasts and Radio will get their own pages under a section named Stream or something.

**Comment by systems-rebooter** [comment]
Thanks for awesome client. Maybe youtube as external source will be valuable as well?

**Comment by dirkgroenen** [comment]
You're welcome, good to hear you like it! Youtube could be an option, but for know I keep it to the extensions listed above. But maybe this changes, when I start developing.

**Comment by systems-rebooter** [comment]
Got it. Thanks @dirkgroenen

**Comment by dirkgroenen** [comment]
I've written a little document containing my ideas about Mopify's new version. Please let me know if you have feedback or suggestions! :)

https://github.com/dirkgroenen/mopidy-mopify/blob/v2.0/pre-work/v2.0/docs/2.0-ideas.md

**Comment by muhahacz** [comment]
+1 for youtube support
It would be great if you could add youtube playlists with settings to have actual version of playlist from channel.
I wrote a bash script to parse songs from specific playlist to m3u triggered by cron every day.
So i have every day actual playlists. Its not perfect i know. Take a look
https://github.com/muhahacz/youtube-playlist-grabber-mopidy-youtube/blob/dev/ypgmy.sh
This plugin handle playing from youtube. Mopidy streams are slow, aprox 10 seconds to buffer, this pafy plugin handle it for 5 seconds to start. You just need prefix song url with yt:
https://github.com/mopidy/mopidy-youtube

For me is youtube better that soundcloud, there are many great music channels.
Consider support of youtube. There are not many server players, that can handle it.
Thanks

**Comment by nebulade** [comment]
A soundcloud integration would be really awesome. Thanks for the great client!

**Comment by dirkgroenen** [comment]
There are some things happening in my life at the moment (good ones, luckily) which reduce my free time to spent on this project. I do have some great ideas for this player or it's successor which I hope to be able to start on very soon.

Soundcloud and local file are definitely something which will be added to the player. They both already exist and work in the development branch.

**Comment by mirkan** [comment]
More sources would be the only real the missing for me from this extension, preferably local och youtube. Anyway thanks and keep it up!

**Comment by dirkgroenen** [comment]
There has been a little progress lately with the new Collection Browser. The idea behind it is making some sort of directory based  browsing through the supported services. 

A little preview: 
![http://i.imgur.com/Q306fiV.png](http://i.imgur.com/Q306fiV.png)

At the moment I've added Spotify, SoundCloud and Local Files as supported browse mediums and I'm planning to do a pre-alpha release soon to get some feedback from you guys.

**Comment by clawoflight** [comment]
I'm impressed with the looks of the search. That's a very clean way to separate the sources :)

**Comment by likeitneverwentaway** [comment]
Soundcloud integration would make Mopify absolutely perfect, the only thing it lacks imo. The search looks GREAT, can't wait for the pre-alpha.

**Comment by dirkgroenen** [comment]
The v2.0 branch contains support for SoundCloud. The only thing I have to finish is the new browse section.

@likeitneverwentaway Since I'm not really a heavy SoundCloud user I would like to know how (and if) you use some of soundclouds browse/playlist functions? Or do you (and other who like the feature) just use it icw search?

**Comment by likeitneverwentaway** [comment]
As a heavy user I mainly use it to browse my playlist, liked songs, and my stream. This is the most important. Do you use Kodi ? The soundcloud add-on is perfect: you can browse your likes, stream, and the users you're following almost never use their discover feature, but obviously I often use the search.

I heavily explored their api, let me know if you need help.

**Comment by frozen1900** [comment]
+1 for mopidy-stream/radio, would be the perfect UI with this feature

**Comment by albino71** [comment]
Hi Dirk,

Not being able to play webradio streams is keeping me from changing to your beautiful looking mopidy-mopify. My wife likes her radio, so...

I saw it's on the todo list, so thats great.
Any chance this will be added anytime soon, or maybe it is possible to name an ETA?

I know this is all free, so the question is absolutely not to put pressure on things of course.

Big thanks for all your hard work!
