### ISSUE TITLE
[idea] Create a Slack/Gitter chatroom

### ISSUE THREAD

**Issue by agboom** [dirkgroenen/mopidy-mopify#114]
Keeps the issue tracker clean, while communicating quick stuff ;)

**Comment by dirkgroenen** [comment]
If you, or other developers, want to start developing on Mopify (which would increase the participants) that would be a fine for me. At the same time I would like to see main communication stay in the Github issues.

**Comment by jodal** [comment]
You're also welcome to use the #mopidy IRC channel at freenode for any
Mopidy related project. Logs of the chat is publicly available, so you
don't have to stay connected all the time to keep up.
