### ISSUE TITLE
Play by script

### ISSUE THREAD

**Issue by tatoosh** [dirkgroenen/mopidy-mopify#115]
How can i play a spotify playlist with a bash script. i want to connect IR Sensor and put the digit 0-9 for my favourite playlists.

Thx

**Comment by dirkgroenen** [comment]
This isn't the correct place for your question. ;) If you want to control Spotify using a bash script you might want to do some Spotify CLI searching on [Google](https://www.google.nl/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=spotify%20cli%20linux).

**Comment by jodal** [comment]
Or if you actually intend to load a Spotify playlist in Mopidy, the
question is not specific to Mopify, a Mopidy web client. The correct medium
to ask about this is https://discuss. mopidy.com.

(The answer either involves the mpc command line client for Mopidy's MPD
server, or curl to make a request to Mopidy's HTTP API.)
