### ISSUE TITLE
Spotify Service connection fails

### ISSUE THREAD

**Issue by dimul** [dirkgroenen/mopidy-mopify#116]
Entered credentials into required fields, allowed access to account by mopidy, popup went away, but still Spotify service is shown as disconnected and no info is present

**Comment by Findus1994** [comment]
Same here.

**Comment by dirkgroenen** [comment]
Which browser are you guys using?

**Comment by Findus1994** [comment]
Never thought of this -.- I used Safari (with OS X). Just tried it with Google Chrome and everything works fine. It looks like Safari have trouble with your authorisation process. Maybe there is a fix anyway for this problem, 'cause I'm working with Safari most often. But for the moment thats a work around to use this awesome front end ;)

**Comment by dirkgroenen** [comment]
Just tested it at the office and it indeed looks like Safari has some issues receiving the tokens from the popup. I already know the fix, probably, but I'm a bit short on time at the moment. 

Let me get on this as soon as possible.

**Comment by Findus1994** [comment]
No to hurry up at the highest priority for me. I'm happy you are working that activly on the project for free. So just let me say thank you for that ;)

**Comment by dirkgroenen** [comment]
The current authentication flow uses localStorage for exchanging keys; looks like something isn't working properly with that.

I've changed it to cookies and it looks like it's working now, can you guys validate this? You don't have to update Mopify.

**Comment by Findus1994** [comment]
Just testet it out. Everything looks ok now. I have the Spotify service connected and I'm able to fetch my songs from my library. I think you can close this issue as fixed. Thanks for your efforts :+1:

**Comment by dirkgroenen** [comment]
Great!
