### ISSUE TITLE
Add button to stop playback

### ISSUE THREAD

**Issue by ghost** [dirkgroenen/mopidy-mopify#117]
It would be really nice to have a button to stop playback, not only pause it.
I run mopidy parallel with kodi, and mopidy wont release the audio driver if playback is only paused.

**Comment by dirkgroenen** [comment]
Let me mark it as an idea. I personally don't like adding a stop button in the controls, but I could also add a shortcut for it.

**Comment by StanSvec** [comment]
Yes, please consider it, because this can be very useful for some users. Recently discussed also in Mopidy issue tracker:  https://github.com/mopidy/mopidy/issues/1384

**Comment by dirkgroenen** [comment]
I'm not really feeling like adding a separate button, but would a context menu on the player or something help for you?

**Comment by StanSvec** [comment]
Anything like this would be perfectly fine for me. Many thanks.

**Comment by dirkgroenen** [comment]
Just released a new version which has an extra shortcut to stop playback. `ctrl+s`

**Comment by StanSvec** [comment]
That was quick! Thanks a lot!
