### ISSUE TITLE
Mopify causes Mopidy tests to fail

### ISSUE THREAD

**Issue by dbrgn** [dirkgroenen/mopidy-mopify#119]
When mopify is installed, the test `tests.test_help.test_help_has_mopidy_options` fails.

The reason is the following code in `mopidy_mopify/sync.py`:

```python
class Sync:                                                                                         
    # Define variables                                                                              
    userhome = os.getenv("HOME")                                                                                                                                                                            
    directory = ".config/mopidy-mopify"                                                             
    filename = "sync.ini"                                                                           
                                                                                                    
    # build path                                                                                    
    syncfile = os.path.join(userhome, directory, filename)                                          
                                                                                                    
    # check if path exists, otherwise create it                                                     
    def __init__(self):                                                                             
        if not os.path.exists(os.path.join(self.userhome, self.directory)):                         
            os.makedirs(os.path.join(self.userhome, self.directory))                                
```

In the context of a test run, `HOME` is not defined. You should never rely on it.

Also, this code creates directories on the file system, even when simply instantiated. Such side effects are a bit dangerous.

I'm not sure what the correct fix would be, as I've not yet understood what the Sync class does :)

**Comment by dirkgroenen** [comment]
Thanks for the note. The sync class takes care of writing the sync options to a file on the Mopidy server. That way other Mopify clients can use the same settings and Spotify credentials, without having to login or what so ever. 

Any sugegestion for a better solution is welcome. I'm aware of the fact that some code might not be good, since I've never touched Python before.

**Comment by blueyed** [comment]
Any update on this?
I was about to report the same issue.  A fix/workaround for mopidy's tests was submitted at https://github.com/mopidy/mopidy/pull/1337.

I think the directories/files should be created on demand only, and the whole procedure(s)/class should be skipped in case $HOME is not defined.  In this case a warning should be logged.

**Comment by dirkgroenen** [comment]
I'm sorry, I'm really busy at the moment. Let me get onto this as soon as possible. If you feel like you're always allowed to make a pull request ;)

**Comment by dirkgroenen** [comment]
If you can head me up on how to run the tests including mopify as a client I will check it out.

**Comment by blueyed** [comment]
I had just installed mopify systemwide and then created a virtualenv for mopidy's test, with `--system-site-packages`, which then makes mopify available during mopidy's test run.

    pyenv virtualenv -p $(PYENV_VERSION=system pyenv which python2.7) --system-site-packages system mopidy

**Comment by dirkgroenen** [comment]
As I see and I'm capable of replicating this error. Let me find out if I'm able to fix this quickly, cause I know the whole python part is a bit of a mess in the current versions.

**Comment by dirkgroenen** [comment]
Should be fixed in the new release.

**Comment by blueyed** [comment]
Thanks!
