### ISSUE TITLE
Party mode / Multi user / Lockdown or what ever you want to call it

### ISSUE THREAD

**Issue by dal00** [dirkgroenen/mopidy-mopify#121]
I would like to be able to lock down modifications to the Spotify account.
For example to be able to share an account connected to speakers at work. It would be nice to limit peoples ability to fill up my Spotify account with random playlists or delete stuff.
### Outline:
- Hide playlists.
- Read only playlists.
- Client side playlists.
- Only be able to create playlists within a special folder on the account

**Comment by dirkgroenen** [comment]
For know I don't think it's worth putting that much hours in creating this service. Although, I would like to know if more users are interested in this, so I'll keep this issue open.

**Comment by synth** [comment]
+1 I'd like friends to be able to come over and connect to mopify on their own device and be able to select songs from my playlists but not modify it. Ideally, they would have the option to connect their own spotify account on their device to play their own playlists.

**Comment by fekete-robert** [comment]
+1, we use mopidy/mopify to listen to music in our room at work, and it would be great to disable changing account settings
