### ISSUE TITLE
Playlist Limits

### ISSUE THREAD

**Issue by tristanbettany** [dirkgroenen/mopidy-mopify#122]
I thought it might be worth mentioning a feature that could be rather handy. Currently I notice that when loading playlists they are limited to 50 in the get request yet I am currently following a few hundred playlists in my account.

Would it make sense to have one of the following options?

- Allow limits to be user defined in the settings
- Add a "Show more playlists" button at the bottom of the page to load in the next 50 playlists
- Have the next 50 playlists lazy load in when scrolling reaches the bottom of the page.

**Comment by dirkgroenen** [comment]
The [`playlistmanager.service`](https://github.com/dirkgroenen/mopidy-mopify/blob/master/src/app/services/playlistmanager.service.js#L55) is already loading all your playlists when Spotify returns a next url.

I've just tested it and looking at the requests the browser is making it is still working. Are you sure your playlists aren't loaded? 

![](http://i.imgur.com/b2rmPbY.png)

**Comment by tristanbettany** [comment]
Thanks for taking a look for me. Yes you are right the requests are being made with the correct offsets and the responses return the expected json. 

When Mopidy loads on the command line it prints that 102 playlists have been loaded, so the 3 requests modify is making is the correct amount to retrieve 102 playlists.

However only the first 51 are displayed in the UI. In order of latest added first. Ive tested this on Safari, Chrome and Firefox. The HTML for the missing playlists is not in the DOM, maybe the extra requests are not being processed and output into the UI?

**Comment by dirkgroenen** [comment]
Hmm that's weird. I personally have an account with 95 playlists which are all displayed. Let me test if something goes wrong when adding 6 playlists and get back on this.

To be sure: you are using the Spotify service as playlist source and not Mopidy?

**Comment by tristanbettany** [comment]
Yeah I tried toggling that and it changed to use some playlists that look like default ones, with strange names. Its certainly using the spotify service. :)

**Comment by dirkgroenen** [comment]
Hmm, just added some playlists to my account and noticed the same problem. When a third request has to be made it only shows 54 playlists (in my case). 

Let me check this out, thanks.
