### ISSUE TITLE
Not all playlists are displayed

### ISSUE THREAD

**Issue by madpsy** [dirkgroenen/mopidy-mopify#124]
I have at least 100 playlists, however they don't all display in the 'Playlist' section. Seems it stops at around 58.

In case this is related:

search_album_count = 200
search_artist_count = 200
search_track_count = 200

Current version: 1.5.4

**Comment by jodal** [comment]
Mopidy-Spotify's search limits are not related to the amount of playlists you receive. Mopidy-Spotify does not limit the number of playlists.

**Comment by dirkgroenen** [comment]
This is related to #122 and has already been fixed in 1.5.5. I hope to release this version soon.

**Comment by madpsy** [comment]
Perfect thanks.
