### ISSUE TITLE
Issues when using mod_proxy

### ISSUE THREAD

**Issue by madpsy** [dirkgroenen/mopidy-mopify#125]
Not sure if this is a mopidy or mopify related issue (new to this) but I've managed to get mopify working behind an Apache based proxy.

This is on a raspbian so required a manual build of the websocket proxy module backported from Apache 2.4. None the less it works with this config:

 ProxyPass /mopidy/ws ws://192.168.0.4:6680/mopidy/ws
 ProxyPassReverse /mopidy/ws ws://192.168.0.4:6680/mopidy/ws
 ProxyPass /mopify/queuemanager ws://192.168.0.4:6680/mopify/queuemanager
 ProxyPassReverse /mopify/queuemanager ws://192.168.0.4:6680/mopify/queuemanager
 ProxyPass / "http://192.168.0.4:6680/"
 ProxyPassReverse / "http://192.168.0.4:6680/"

This gives me some advantages:

1) IPv6 support 
2) SSL Support
3) Authentication support (with standard Apache allow/deny stuff)

The only problems I have are:

1) Chrome and other behaved browsers don't allow insecure websocket requests when using an HTTPS site.
2) The port for mopidy (in mopify's Settings) needs set to 80 (or 443 if SSL worked)

I've no idea how to fix 1) as ws:// seem hard coded in the mopify JS. Issue 2) is less of an issue as it can be set in Settings but would maybe be nice to somehow set it somewhere else for convenience when I use a new client - possibly push it out with the nice Synchronise service.

**Comment by madpsy** [comment]
I notice in /static/debug/src/vendor/mopidy/mopidy.js:

{code}
Mopidy.prototype._configure = function (settings) {
    var protocol = (typeof document !== "undefined" &&
        document.location.protocol === "https:") ? "wss://" : "ws://";
    var currentHost = (typeof document !== "undefined" &&
        document.location.host) || "localhost";
    settings.webSocketUrl = settings.webSocketUrl ||
        protocol + currentHost + "/mopidy/ws";
{code}

Which all looks good an well, but I also see in /static/debug/src/app/services/mopidy.service.js:

{code}
        // Initialize mopidy
        try {
          this.mopidy = new Mopidy({
            webSocketUrl: 'ws://' + mopidyip + ':' + mopidyport + '/mopidy/ws',
            callingConvention: 'by-position-or-by-name'
          });
{code}

Which seems pretty hardcoded to use ws://

I'm tempted to do s/ws\/\/:/wss:\/\//g and see what happens :)

**Comment by dirkgroenen** [comment]
Let me change the websocket connection to wss based on the current connection. As of the synchronization service: I was already planning on adding the 'Settings' section to it, but since you've mentioned it now I'll move it forward to 1.5.5.

**Comment by madpsy** [comment]
Excellent thanks - if you need me to test anything please let me know. I've installed via pip so not sure if that impacts how I would install a version to test.

**Comment by dirkgroenen** [comment]
You can install a 'live' version by using `pip install https://github.com/dirkgroenen/mopidy-mopify/archive/master.zip`. But for now this should be easy to test without a proxy. 

I'll let you know when I've made some progress, working on it right now.

**Comment by dirkgroenen** [comment]
I've just packaged 1.5.5 and I'm uploading it as we speak. You should be able to download the latest version within a few minutes.

**Comment by madpsy** [comment]
Great stuff! Thanks again.

**Comment by madpsy** [comment]
Very close!

Mixed Content: The page at 'https://xxxxxxxxx/mopify/' was loaded over HTTPS, but requested an insecure resource 'http://mopify.bitlabs.nl/auth/spotify/frame/'. This request has been blocked; the content must be served over HTTPS.

Not sure who owns https://mopify.bitlabs.nl/auth/spotify/frame/ but looks like it's SSL and non SSL content differs.

mopidy-mopify-1.5.5.js:11 Mixed Content: The page at 'https://xxxxxxxxx/mopify/#/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://mopidy.link9.net:443/mopify/sync/settings'. This request has been blocked; the content must be served over HTTPS.

That looks simple enough.

mopidy-mopify-1.5.5.js:12792Mixed Content: The page at 'https://xxxxxxxxx/mopify/#/music/playlists' was loaded over HTTPS, but requested an insecure script 'http://mopify.bitlabs.nl/api/post/?callback=angular.callbacks._1&data=%7B%2…D&url=http:%2F%2Fdeveloper.echonest.com%2Fapi%2Fv4%2Ftasteprofile%2Fupdate'. This request has been blocked; the content must be served over HTTPS.

That one works over HTTPs

**Comment by madpsy** [comment]
One more:

Mixed Content: The page at 'https://xxxxxxxxxxxx/mopify/#/music/tracklist/spotify:user:xxxxxxxxx:playlist:6h6MT9xS8lOhglZqSWduo3/Xen%20Cuts' was loaded over HTTPS, but requested an insecure font 'http://fonts.gstatic.com/s/robotocondensed/v13/b9QBgL0iMZfDSpmcXcE8nBBQ_Gf4FfI8J4SYljBAylk.woff2'. This content should also be served over HTTPS.

This one probably is the same as the other Settings one:

XMLHttpRequest cannot load http://xxxxx:443/mopify/sync/settings. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://mopidy.link9.net' is therefore not allowed access.

(the port is coming from the port in Settings which is fine, except of course the protocol.)

**Comment by madpsy** [comment]
Despite the 'http://xxxxx:443/mopify/sync/settings' error, which there's no getting around manually, as long as I tell Chrome to allow mixed content then the other insecure requests are allowed and everything appears to work, which is good news :-)
