### ISSUE TITLE
Volume in 'mobile' mode fails

### ISSUE THREAD

**Issue by madpsy** [dirkgroenen/mopidy-mopify#127]
When using the mobile version of the volume control it fails with:

Server returned error: Object {message: "Application error", code: 0, data: Object}
code: 0
data: 
Objectmessage: "Expected an integer, not 56.81818181818182"

Version 1.5.5 also happened in 1.5.4

**Comment by madpsy** [comment]
This also occurs on the normal volume control, I guess it's hit or miss if the value lands on an integer or not. Some rounding or similar is likely in order.

**Comment by dirkgroenen** [comment]
Hmm never experienced this, but I'll add a rounding to be sure.

**Comment by jodal** [comment]
This probably surfaced only recently because Mopidy 1.1 started enforcing the documented API with lots of type checks.

**Comment by dirkgroenen** [comment]
Ah I see, didn't notice a new release of Mopidy. I've just uploaded version 1.5.6 which fixes this issue.
