### ISSUE TITLE
Music/Bio/Related links only display on large windows

### ISSUE THREAD

**Issue by madpsy** [dirkgroenen/mopidy-mopify#128]
When on an Artist page the links to Music/Bio/Related are only displayed when the browser window is fairly large.

They never appear in mobile mode.

http://i.imgur.com/ZUBNQJW.png
http://i.imgur.com/9FzUIGt.png
http://i.imgur.com/PblwBaC.png

**Comment by dirkgroenen** [comment]
I'm planning to change the artist page somewhere in the future, so I won't do anything with this for now since I've already got the whole version 2 on my plate. 

I'm going to bookmark this as a version 2.0.0, but I can't promise anything.
