### ISSUE TITLE
Protocol detection should be used for all absolute URLs

### ISSUE THREAD

**Issue by madpsy** [dirkgroenen/mopidy-mopify#129]
Following on from #125 as that's now closed.

Protocol detection should be used to avoid mixed content errors. Using 'document.location.protocol' is probably the way to go here.

Errors when using HTTPS I've found so far:

Mixed Content: The page at 'https://xxxxxxxxx/mopify/' was loaded over HTTPS, but requested an insecure resource 'http://mopify.bitlabs.nl/auth/spotify/frame/'. This request has been blocked; the content must be served over HTTPS.

Not sure who owns https://mopify.bitlabs.nl/auth/spotify/frame/ but looks like it's SSL and non SSL content differs.

mopidy-mopify-1.5.5.js:11 Mixed Content: The page at 'https://xxxxxxxxx/mopify/#/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://mopidy.link9.net:443/mopify/sync/settings'. This request has been blocked; the content must be served over HTTPS.

That looks simple enough. It's reading the port from 'Settings' but not doing protocol detection.

mopidy-mopify-1.5.5.js:12792Mixed Content: The page at 'https://xxxxxxxxx/mopify/#/music/playlists' was loaded over HTTPS, but requested an insecure script 'http://mopify.bitlabs.nl/api/post/?callback=angular.callbacks._1&data=%7B%2…D&url=http:%2F%2Fdeveloper.echonest.com%2Fapi%2Fv4%2Ftasteprofile%2Fupdate'. This request has been blocked; the content must be served over HTTPS.

Again, that should be https and mopify.bitlabs.nl needs its SSL config 'fixed'.

Mixed Content: The page at 'https://xxxxxxxxxxxx/mopify/#/music/tracklist/spotify:user:xxxxxxxxx:playlist:6h6MT9xS8lOhglZqSWduo3/Xen%20Cuts' was loaded over HTTPS, but requested an insecure font 'http://fonts.gstatic.com/s/robotocondensed/v13/b9QBgL0iMZfDSpmcXcE8nBBQ_Gf4FfI8J4SYljBAylk.woff2'. This content should also be served over HTTPS.

gstatic.com is https ready.

XMLHttpRequest cannot load http://xxxxx:443/mopify/sync/settings. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://mopidy.link9.net' is therefore not allowed access.

This one probably is the same as the other Settings.

**Comment by madpsy** [comment]
All looking good now! Thanks again, much appreciated.

**Comment by dirkgroenen** [comment]
You're welcome ;)

**Comment by madpsy** [comment]
Hopefully the last one!!

http://developer.echonest.com/

That still seems to be called over HTTP, it has HTTPS support already albeit with a SHA-1 signature :)

**Comment by dirkgroenen** [comment]
Jup I noticed that one, but when I tried the url over https I ended up with an error. I don't understand why, cause it seems to work when I look at it now. I'll change it asap.

**Comment by madpsy** [comment]
Even firefox loads it - who seem to be on a crusade after all the recent SSL vulnerabilities. Chrome is happy enough too (for now), although they should probably get a new cert generated out of general good practice.

**Comment by dirkgroenen** [comment]
I've just released 1.5.7. It has been a bit of a messy version updating the last days so hopefully everything is working properly now.
