### ISSUE TITLE
INVALID_CLIENT: Invalid redirect URI

### ISSUE THREAD

**Issue by madpsy** [dirkgroenen/mopidy-mopify#131]
Possible regression in 1.5.6.

When logging into Spotify I get 'INVALID_CLIENT: Invalid redirect URI' back from spotify. This happens both through my proxy configuration and when using the native mopidy URL. 

URL of the login frame is:

https://accounts.spotify.com/authorize?client_id=b6b699a5595b406d9bfba11bee303aa4&redirect_uri=https%3A%2F%2Fbitlabs.nl%2Fmopify%2Fauth%2Fspotify%2Fcallback%2F&scope=user-read-private%20playlist-read-private%20playlist-modify-private%20playlist-modify-public%20user-library-read%20user-library-modify%20user-follow-modify%20user-follow-read&response_type=code

Please let me know a paypal donate link too :)

Thanks.

**Comment by dirkgroenen** [comment]
Ah f*uck, completely forgot to add the new domain to the API whitelist. Kinda weird that the error didn't popup on my screen. 

A donation link is placed next to the version and downloads badges in the readme. Probably ain't clear enough? For your comfort: here's the link to [PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=QUDAJBCJVP2G6). :wink:

**Comment by madpsy** [comment]
It didn't occur for me either while at work but did at home :)

Now getting a different error:

Something wen't wrong...

Looks like Spotify didn't return the correct tokens. Please close this window and refresh Mopify.

URL was: https://bitlabs.nl/mopify/auth/spotify/callback/?code=<massive uuid of sorts>

(Tried incognito too.)

**Comment by dirkgroenen** [comment]
Hmm quite weird... Let me get into this.

**Comment by madpsy** [comment]
If you want the source IP or the token value please ask.

**Comment by dirkgroenen** [comment]
It's happening to me too now, so I don't think I need any of that.

**Comment by dirkgroenen** [comment]
Should be working again!

**Comment by madpsy** [comment]
Weyhey! Looking good to me! :) 

Thanks again.

**Comment by wilderkaiser** [comment]
Hi togehter and first of all let me thank Dirk for this great UI and much more :-) I have the same token things-dings-ups --- from Spotify: 

Something wen't wrong... blabla 

Any idea??

**Comment by dirkgroenen** [comment]
Hmm, how does your URL look (in the "Something went wrong window) and which browser are you using?

**Comment by wilderkaiser** [comment]
HI ... late but i get back to this today ;-) https://bitlabs.nl/mopify/auth/spotify/callback/?code=AQDo0eE6ZCSJoeSytLiHCWpur5ppq0hbEAEtgajuDv_BKnvVIh9Jredl8Gw91pLCAaz_0tMMdeDRoklzIa6EgfD-3gIeWrGir3P8ctR2TXjnqX_izm9SFJ5n7f6ma4pusfxFqm9Ksd7jJFT6tMvK_Gtu0o5VZKGD3MKdbUXddNlEmkmAa0muEaBJnEoopi90MY48O6Bz2Vqb52Tt1-CXH0e9Z-mPSz0C3BtCtN_l5599kIA88y_da6C50F3_Dc2mptmxAE32KgV0_O6QxUFXPWrxCKrfW3HyyBj66IEYKCevp2mtxSMHvNIH83-5oyI_d6PrkLn-8mc8WyBZBCGBYA

**Comment by Leftylady** [comment]
Hey, sorry to butt in, but I came upon this while trying to debug this issue. I have changed my callback uri in my code and I can host page, but after logging back with spotify it redirects to an old IP for an old instance. Do you guys mind sharing your fix?
