### ISSUE TITLE
Spotify plugin not loading after upgrade of mopify

### ISSUE THREAD

**Issue by tristanbettany** [dirkgroenen/mopidy-mopify#133]
So this is an odd one,

I ran this command this morning ```sudo pip install --upgrade Mopidy-Mopify``` to upgrade mopify. Everything went smoothly  and then I noticed nothing was playing from spotify after rebooting mopidy. 

I checked the output and noticed this:

```INFO Enabled extensions: mopify, mpd, http, file, stream, m3u, softwaremixer, moped, local 
INFO Disabled extensions: none```

This was weird I thought, so I made sure it was installed with this ```sudo apt-get install mopidy-spotify``` which gives this:

```mopidy-spotify is already the newest version.```

So I removed it like so ```sudo apt-get remove --purge moped-spotify``` and then installed it again. No success in it loading though

Next I removed the config directory for spotify in ```~/.config/mopidy/spotify``` as I heard that can have cache issues. Still it didn't load.

Finally, I went to the main config and removed my username and password which the plugin would usually complain about needing one if you did that and still nothing. 

Lastly I Rebooted and again nothing. Im not sure how upgrading mopify could have affected the spotify plugin so badly but it seems to have done so.

I was hoping you might be able to shed a little light on the situation. Thanks

**Comment by dirkgroenen** [comment]
I'm not sure what is happening here and you might want to open an issue in the mopidy-spotify repo for better help. Is it possible that you have a double installation of mopidy-spotify? One through pip and one through the package manager for example?

**Comment by kingosticks** [comment]
Have a quick look at the last bullet point at https://docs.mopidy.com/en/latest/debian/ and check that it all matches up with your system.

**Comment by tristanbettany** [comment]
The spotify plugin is installed in the directory ```/usr/share/mopidy``` it seems. I tried installing it with pip based on this from the documentation ```"Mopidy installed with pip can use extensions installed with pip, but not extensions installed from a Debian package released before August 2015."``` and it seemed to throw a lot of errors

e.g. 
```Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found```
```Command python setup.py egg_info failed with error code 1```

Not 100% sure what to do about these, I tried copying over the folder from one dir to the other but it doesn't seem to have any affect.

Thanks for your help guys :)

**Comment by kingosticks** [comment]
I'd suggest removing the pip installed versions of mopidy and mpoidy-spotify, and then installing everything from APT. Copying over folders is probably not a good idea, let your system package manager sort this all out (including those missing libffi dependencies that pip cannot find).

**Comment by tristanbettany** [comment]
Morning,

So I tried the things you suggested. it seems i might have 2 installations of mopidy itself. so i uninstalled the pip one and the apt one. even after that mopidy still worked so i can only assume pip did nothing. I thought I would give installing spotify extension via pip a go, there were about a million different things pip complained about like gcc, libffi etc etc. I even had to install python dev tools. However I managed to get it to this state when mopidy runs...

```INFO     Disabled extension spotify: pyspotify>=2.0.2 required, but found pyspotify 1.11 at /usr/lib/pymodules/python2.7
INFO     Enabled extensions: mopify, mpd, http, file, stream, m3u, softwaremixer, moped, local
INFO     Disabled extensions: spotify```

not really sure why pip would have installed a old version but i tried ```--upgrade``` and then I just get more errors of this ...

```build/temp.linux-x86_64-2.7/spotify._spotify.c:391:28: fatal error: libspotify/api.h: No such file or directory
    compilation terminated.
    error: command 'gcc' failed with exit status 1```

Not really sure my installation is fixable or even un-installable without re-installing the whole machine. :( What do you think?

**Comment by tristanbettany** [comment]
Also ```sudo apt-get install mopidy-spotify``` now does this for some bizarre reason

```The following packages have unmet dependencies.
 mopidy-spotify : Depends: python-spotify (>= 2.0.2) but 1.11-0mopidy1 is to be installed
E: Unable to correct problems, you have held broken packages.```

**Comment by kingosticks** [comment]
Pyspotify depends on packages that are not available on pip and which you
should install via other means (e.g. from apt). This should be in the
pyspotify documentation. Fully removing the pip Mopidy install and
installing via apt would prevent issues like this. You should be able to
manually remove the pip installed files. You might want to have a look for
similar issues or post at discuss.mopidy.com since this isn't really a
mopify problem.

**Comment by dirkgroenen** [comment]
I'm going to close this one. If you need extra help you can follow kingosticks tips and use the Mopidy forum or the Mopidy-Spotify repository.
