### ISSUE TITLE
Authenticated services only stay authenticated for current browser session?

### ISSUE THREAD

**Issue by consti** [dirkgroenen/mopidy-mopify#135]
I just integrated mopify at work – it looks great!

We want to use it as our shared music player (we have a spare machine that's connected to a speaker).

I noticed that the client stops playing as soon as I close the browser window – and each user would have to authenticate to spotify on their own. Is there a way to keep the services authenticated for all clients?

Thanks.

**Comment by dirkgroenen** [comment]
Thanks!

I have never seen that behavior before and to be honest I can't think of a way how Mopify would stop Mopidy from playing when closing the browser. Are you sure it's Mopify which stops Mopidy?

About the Spotify authentication: as long as you're logged in to Spotify Mopify should automatically refresh the tokens using the refresh token. If you want all clients to use the same Spotify account you can use the Sync Service (you can read more about that in the wiki).
