### ISSUE TITLE
Spotify Connection fails

### ISSUE THREAD

**Issue by uncles-a-m** [dirkgroenen/mopidy-mopify#136]
Hi,

first of all, thanks for the great work and beutiful interface!

I've installed mopify yesterday, but i cannot connect to spotify. When I login into spotify, I get the message:

"Something wen't wrong...

Looks like Spotify didn't return the correct tokens. Please close this window and refresh Mopify."

What is my mistake?

**Comment by dirkgroenen** [comment]
Can you check the URL of the popup when your seeing the error page and drop it here? I haven't experienced this issue with the current version.

**Comment by uncles-a-m** [comment]
Hi Dirk,

thank's for your reply. 

I've used a fresh install of Pi MusicBox 0.6. 
There was my fault: there was an old version of Mopify in the image. 
After upgrading to version 1.5.7 the connection worked. But then, I had a new issue. I could not access my LocalMedia and Spotify playlists from MusicBox-Webclient anymore.
After reading the log, I experienced, that the import of the module "utils" failed. 
Hence, I've compared the MusicBox-Image with my installation and, indeed, the folder "utils" inside "/usr/local/lib/python2.7/dist-packages/mopidy" was missing!

Can this be a result of upgrading mopify???

It's getting even worse: I did "pip install utils" to get the module, but it was not installed into the mentioned folder. Thus, I copied the folder from the image back to my installation and performed "mopidy local scan" and everything seemed to work. BUT now, after a reboot, I cannot access the Webfrontend anymore. My browser sais that the connection is refused. However, connection via ssh is working. But I just can't fix it...

Next step would be to clean the card and put the image again to the card. But I am afraid, that the upgrade of mopify will break the system again...

**Comment by kingosticks** [comment]
Musicbox has lots of old versions and unfortunately doesn't support updating. Doing so will almost certainly leave your system in a mess. You can follow the unofficial updating guide at http://pimusicbox.readthedocs.org/en/develop/upgrading/ but it's probably outdated now.

**Comment by kingosticks** [comment]
(this probably isn't a mopify issue)

**Comment by uncles-a-m** [comment]
I agree. Thank you for your help.
I will reinstall pi music box and try to build my own installation with arch and mopidy on asecond card.

Sorry for the incovenience. I will close this now.
