### ISSUE TITLE
Add custom context menu to currently played song bar

### ISSUE THREAD

**Issue by nebulade** [dirkgroenen/mopidy-mopify#137]
It would be useful to have the same custom context menu, like in playlists, for the currently played song bar, or just the Song-Artist link/label.
So far when I listen to a radio stream and would like to add the current track to a playlist, I have to click on that link and then search for it in the artist/song/album view, to right-click and add it to a playlist.

**Comment by dirkgroenen** [comment]
Sounds good for me. :+1:
