### ISSUE TITLE
[Idea] Fullscreen current track info

### ISSUE THREAD

**Issue by olkkoo** [dirkgroenen/mopidy-mopify#138]
Some Spotify clients like Spotify for iPad has a mode where the current track info is displayed fullscreen. This would be perfect for parties and having friends come over. They could just see Next/Previous/Pause controls, track info and perhaps artist bio. There is no need to lock down any functionalities but just to create a view showing the aforementioned info. A screenshot can be found [here](http://ipadinsight.wpengine.netdna-cdn.com/wp-content/uploads/2012/06/Spotify-for-iPad.jpg).

**Comment by mjbroekhuijsen** [comment]
Old post, but +1, perhaps for 2.0 version?

**Comment by BLX-S** [comment]
Good idea, I might see if I can design something up for the next release when I have some spare time.
