### ISSUE TITLE
Small screen support

### ISSUE THREAD

**Issue by vdbee** [dirkgroenen/mopidy-mopify#14]
Although I understand it is written for larger screens I tried to load the page in my Nexus 7. It has quite some difficulties with showing the page. I attached a screenshot of my phone that shows similar behavior.

I tried Chrome and Firefox and tried the "desktop mode" as well.  

![screenshot_2015-01-04-19-45-59](https://cloud.githubusercontent.com/assets/3402649/5607272/b29a4e22-9454-11e4-875f-963fae873bba.png)

**Comment by dirkgroenen** [comment]
I haven't done anything with mobile devices yet. At the moment I'm busy with the folder structure and the basic responsive display. 

If everything goes well I can release it tonight.

**Comment by dirkgroenen** [comment]
I've just released v1.1.x which contains some improvement in the responsive layout. Please remember that I haven't focused on mobile devices yet.

**Comment by dirkgroenen** [comment]
The first responsive implementation has been added in release 1.2.0. Note that this is a 'beta/quick and dirty' version and has only been tested on my Nexus 5.

**Comment by vdbee** [comment]
It works already quite well, thanks! Maybe some thinks to consider:
* The desktop version shows icons (list, play, radio) on the album-art when hoovering over it. Maybe it is possibly to show these options continuously in the responsive version? Maybe not fully opaque?
* Maybe add an option to filter the playlists using the folder structure? Possibly a pull down menu besides the +-icon (the one for adding a playlist) with the folder names?

**Comment by dirkgroenen** [comment]
Thank!

Showing those icons continuously is definitely something I want to put in a next version. Adding the folder structure is something I'll consider.
