### ISSUE TITLE
Havin a forward-slash (/) in your playlist-folders results in display bug

### ISSUE THREAD

**Issue by jh0ker** [dirkgroenen/mopidy-mopify#140]
I have a playlist folder thats named "Albums/Artists". It gets displayed as "Albums", and all containing playlists are named "Artists", instead of their actual names. 
Possibly easily fixed by urlencode-ing album and playlist names.

**Comment by dirkgroenen** [comment]
This is a Mopidy problem. Mopidy-spotify separates folders and lists with a slash. If you want to get rid of this you can use the built in Spotify service as source, but that will also disable the folder functionality.

I think it's best to open an issue for this in mopidy-spotify, maybe they can change anything.

**Comment by jh0ker** [comment]
Thanks, I'll do that!

**Comment by jodal** [comment]
There's nothing wrong in Mopidy-Spotify using slash as the directory separator. It's arguably the most common character to use for that purpose. If that doesn't work for a particular Mopidy frontend or client, it must fix it itself. For example, the Mopidy-MPD frontend replaces slash with pipe to conform to the MPD protocol.

**Comment by dirkgroenen** [comment]
How would it be possible to change the slashes to for example pipes and still keep to know that it's a directory or not? The moment we retrieve the playlists from Mopidy we can't see which slash is used as playlist name and which is used as directory.

**Comment by jodal** [comment]
I don't think there's any fool proof way to do that with the current API. IIRC, there is a suggestion to add a `core.playlists.as_tree()` or similar in the core API plans, but that's not going to land in the near future.
