### ISSUE TITLE
Queued tracks playing bottom-up, not top-down

### ISSUE THREAD

**Issue by nekosaur** [dirkgroenen/mopidy-mopify#141]
I've just installed mopify for the first time and everything seems to work fine, except that after I've added tracks to the queue, they're played bottom-up, starting with the latest song added to the queue, not the oldest one.

When I look at the Current Tracklist page, the tracks are listed in the Queue section the correct order, but when the next song plays it starts from the bottom of the queue.

Am I missing something obvious?

**Comment by nekosaur** [comment]
Don't know if this was the right way to fix it, but I changed the following, starting on line 241 in queuemanager.service.js

```javascript
that.version = response.version;
deferred.resolve(response);
```
to 
```javascript
that.version = response.version;
that.queue = response.queue;
deferred.resolve(response);
```

**Comment by dirkgroenen** [comment]
Hmm I've never seen that behaviour before. This week I'll be heading to Web Summit, I'll get on to this one when I'm back.

**Comment by nekosaur** [comment]
Some more information that might help tracking this down. If I added one track to the queue, then refreshed the page, then added another track, refreshed the page, etc then the added tracks would get played in the correct order. 

It seemed like QueueManager.queue did not get updated by simply adding a track, which meant requests to mopidy to add tracks to the tracklist would always have at_position = 1
