### ISSUE TITLE
Search playlists only

### ISSUE THREAD

**Issue by d3rrial** [dirkgroenen/mopidy-mopify#145]
Currently the search bar connects to spotify and sends a search query that way. Why not make it search through the playlist data first? As it is, whenever I want to get to a specific playlist (for example Soilwork - The Ride Majestic) I have to scroll down through all playlists, because there's no function to just let me listen to that playlist.

Additionally you could also add a "Sort by" in the playlist submenu.
I personally like the standard spotify sort by creation date, others might like things like total play length, name, name z-a, things like that.

EDIT:
To put what I wanted to say in a more readable way:
The search textbox currently passes the search-string to mopidy, as far as I know, and interprets whatever mopidy hands back as the results, mopidy does not do local searches of cached files (For example the list of playlists) it simply passes the query on to spotify. My proposal is to either implement a secondary textbox in the Playlists submenu, or use the existing textbox and include an additional table of local results. The secondary textbox could then be used to filter the existing playlists to only leave desirable results by entering the full or partial name of the playlist (or possibly songs contained within the playlist). (Example: [My m            ] = content of textbox, Results: Playlists{"My music", "My most memorable"})

**Comment by dirkgroenen** [comment]
For now I've added a local playlist search of which the results are added to the top of the list.
