### ISSUE TITLE
Starting from mopify puts mopidy in consume mode

### ISSUE THREAD

**Issue by d3rrial** [dirkgroenen/mopidy-mopify#146]
Sometimes when I start listening to a playlist on mopify, mopidy is set to consume and this mode can't be turned off from within mopify (I have to use ncmpcpp to turn consume off again).
It's hard to reproduce because it happens sporadically and I haven't tracked down the exact issue yet, sorry.

**Comment by dirkgroenen** [comment]
It's indeed correct that Mopify enables consume mode. This has been done to improve the experience of the queue. Though it must be said, this was a piece of code I implemented before writing our own QueueManager. With a few fixes it should be possible to disable this 'feature' and make it possible to go backwards. 

I'll leave this open and try to fix this somewhere in the future.
