### ISSUE TITLE
Playback bar on top

### ISSUE THREAD

**Issue by d3rrial** [dirkgroenen/mopidy-mopify#147]
Maybe add an option to switch the place of the playback bar from the bottom to the top.
My thought behind this is to minimize mouse travel distance: When I'm listening to music, I'm usually also browsing in Chrome, or at least on another tab in chrome while working in another workspace, so when I want to skip, pause, etc. a song, I need to switch tab first in the topmost part of my screen and then move my mouse to use the buttons at the bottommost part of my screen, which isn't exactly efficient.

**Comment by dirkgroenen** [comment]
Hmm I see where this coming from, though I'm not a big fan of adding this 'feature'. I'll leave this issue open in case anybody else feels like they want this feature too. If enough people vote for this I might implement it ;)

**Comment by d3rrial** [comment]
In the worst case you can tell me where in the code the playback bar is handled, I'll fork it, add the option and create a pull request. I'm not a web-developer tho, so this might take a few months or so...

**Comment by dirkgroenen** [comment]
You can get pretty far by just changing some CSS. In the ideal situation you would have to add an option somewhere in the settings area and give the body an extra class. The CSS file should take care of the rest (moving the player to the top and change the bottom padding to a top padding).
