### ISSUE TITLE
support multiple Spotify accounts for streaming

### ISSUE THREAD

**Issue by mrlukasbos** [dirkgroenen/mopidy-mopify#148]
Mopify is running at home in the living room, and it is configured to my own spotify account. However, when one of my housemates wants to listen to some music, and i am somewhere else using spotify (for example on my phone) the music stops at one of these places. My housemates also have spotify premium, so would it be possible to change the config file of mopidy dynamically with the spotify account that is attached to it? Or a switch where the user can choose which spotify account will be used to stream?

**Comment by dirkgroenen** [comment]
This sounds more like a Mopidy issue for me. There would be some really hacky way to achieve this, but that's not something I'm going to invest time in at the moment. 

I'm going to start on building a massive rebuild, as I've been writing down in a few other issues and my blog. There are some ideas about this rebuild to build it without Mopidy and put it on the market as a standalone product. Though, at the moment I'm investigating if this is possible to achieve and what the costs would be. 

For know I'm afraid it won't be possible to switch Mopidy's Spotify user in the Mopidy client.
