### ISSUE TITLE
Bitrate of spotify songs

### ISSUE THREAD

**Issue by af2005** [dirkgroenen/mopidy-mopify#149]
Hi,

at which bitrate are the songs streamed from Spotify? I think the default is 160kb/s. I could not find any settings for that or are you taking the bitrate configured for the spotify extension in the mopidy.conf?

Btw: Awesome web design!! One of the most beautiful interface designs I have seen in the past.

**Comment by dirkgroenen** [comment]
Al the playing and stuff happens in moidy-spotify so you should change the bitrate option for that extension.

Thanks, glad you like the design!
