### ISSUE TITLE
Albums/tracks not loading after upgrade

### ISSUE THREAD

**Issue by madpsy** [dirkgroenen/mopidy-mopify#150]
Hey.

I just upgraded (which may be unrelated as not used for a couple weeks) but now playlists aren't loading and tracks aren't queing.

See screenshot - looks like websockets aren't working - is that a mopidy or mopify issue?

(This time I'm connecting directly to mopidy on the local IP:6680, not using the mod_proxy stuff like before, if you recall. I've tried both ways though.)

Thanks.

![screen shot 2015-12-01 at 20 19 45](https://cloud.githubusercontent.com/assets/13963858/11513093/5a60935a-9869-11e5-8564-6815a6eca702.png)

**Comment by dirkgroenen** [comment]
Hmm looks like something else is going wrong. Looking at your screen the websockets are working fine, but after upgrading my local installation I see an other lookup error popping.

Getting on to this one right now, I'll keep you updated.

**Comment by dirkgroenen** [comment]
Have you checked opening Mopify with something random behind the URL? (like http://localhost:6680/mopify/?v=12312312)

**Comment by madpsy** [comment]
Just tried but no luck - now the console has something though. See screenshot.

![screen shot 2015-12-01 at 22 01 42](https://cloud.githubusercontent.com/assets/13963858/11515717/3558d910-9877-11e5-9832-32f7fc008fe3.png)

**Comment by dirkgroenen** [comment]
Can you check the version number on your settings page and share it? I saw this error happening, but after I made sure I was on the correct version and the cache was empty it all worked again.

**Comment by madpsy** [comment]
![screen shot 2015-12-01 at 22 20 52](https://cloud.githubusercontent.com/assets/13963858/11516203/d2b19d1c-9879-11e5-8ead-1e61b51257d0.png)

**Comment by dirkgroenen** [comment]
I know this wont help you at all, but at no circumstance am I able to recreate your issue. I did see a lookup error appear once during Mopidy startup, but after a browser reload it worked again. 

For now I'll try to continue re-simulate your issue. I've renamed the issue and I'll leave it open in case someone else is having the same issue.

**Comment by madpsy** [comment]
No worries I'll do a bit more debug myself and let you know if I find anything.

Thanks

**Comment by dirkgroenen** [comment]
:+1:

**Comment by madpsy** [comment]
All completely my fault. mopidy-spotify decided it didn't want to be installed anymore. Not sure if there's any sanity checks which can be done to ensure it's there. Shall close.

**Comment by dirkgroenen** [comment]
No problem. It might be possible to detect these kind of issues by doing a random search and check the returning backend libraries. 

I might give this some extra thought when continuing the development on the new version.
