### ISSUE TITLE
Playlist sorting

### ISSUE THREAD

**Issue by helgrind** [dirkgroenen/mopidy-mopify#151]
Hi,

My housemate has some playlists which are in a random order on Spotify, and he refused to use the mopify setup unless he could play back sorted by date added. I have added a button to the playlist view to start a sorted playlist playback, using the same code as the shuffle button but feeding it a copy of the loadedTracks array sorted by an added_at property I fetched from the API (getPlaylistTracks). I figured it might be a nice feature. Let me know if you want any of the code, but I'm sure you would do a better implementation.I was in two minds whether to add the property to the existing list or pull a new tracklist from getPlaylistTracks - but as the former is fetched through the mopidy service I thought I'd leave it.

Cheers.

**Comment by dirkgroenen** [comment]
I'm been figuring this thing out for a while (adding a sort option), but at a certain point I decided to let it be as it is at the moment. The new interface (2.0) will probably have this option build in.

Though, sharing your implementation never hurts. I'm having quite some trouble finding spare time to work on the project. Most of the time I'm able to work on it goes to devving up the new version and setting up everything for the new product.

**Comment by helgrind** [comment]
Yeah, I think it needs a separate sort feature, and then you can submit either the sorted playlist or a shuffled version to the queue. Likewise I am short on time (PhD) but will have a play if and when.
