### ISSUE TITLE
PayPal donation link is broken

### ISSUE THREAD

**Issue by bertm** [dirkgroenen/mopidy-mopify#153]
The PayPal donation link in the About section of Settings appears to be broken. After clicking it, I consistently end up on a PayPal page with the message:

> # Sorry — your last action could not be completed
>
> If you were making a purchase or sending money, we recommend that you check both your PayPal account and your email for a transaction confirmation after 30 minutes.
>
>If you came to this page from another website, please return to that site (don't use your browser's Back button) and restart your activity.
>
>If you came from PayPal's website, click the PayPal logo in the upper-left corner to return to our home page and restart your activity. You might have to log in again.

**Comment by dirkgroenen** [comment]
Thanks for the heads-up, I've just fixed the link and pushed it. Shall be online in the next release. In the meantime the PayPal donation page can be reached through the [button on the README page](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=QUDAJBCJVP2G6).
