### ISSUE TITLE
Volume wrongly calculated from click position

### ISSUE THREAD

**Issue by daviesian** [dirkgroenen/mopidy-mopify#155]
Clicking on the volume bar causes the [volume to be set] (https://github.com/dirkgroenen/mopidy-mopify/blob/8c064d03088336e9e4cb2d2125c974953ccb3df6/src/app/player/controls/controls.controller.js#L108), but there is a bug in the calculation of [`volumeBarWidth`](https://github.com/dirkgroenen/mopidy-mopify/blob/8c064d03088336e9e4cb2d2125c974953ccb3df6/src/app/player/controls/controls.controller.js#L106). If the user happens to click precisely on the [inner `div`](https://github.com/dirkgroenen/mopidy-mopify/blob/8c064d03088336e9e4cb2d2125c974953ccb3df6/src/app/player/controls/controls.right.tmpl.html#L13) then the new volume is calculated relative to the width of the inner `div` (the current volume), instead of relative to the full width of the volume bar.

I would be happy to create a pull request to fix this issue, if it is not already solved in v2.

**Comment by dirkgroenen** [comment]
This isn't already solved in V2, so if you want I would be happy to merge your pull request.

**Comment by daviesian** [comment]
Sure. Which branch would you like me to base my changes on? It's not entirely clear whether to start from `master`, `development` or `v2.0`.

**Comment by flozano** [comment]
THANKS
