### ISSUE TITLE
Cannot connect to Spotify service

### ISSUE THREAD

**Issue by minigopher17** [dirkgroenen/mopidy-mopify#158]
Hi

While trying to connect to the Spotify service, the popup asks for Spotify details but it then displays this message:

Something wen't wrong...
Looks like Spotify didn't return the correct tokens. Please close this window and refresh Mopify.

URL in popup is: https://bitlabs.nl/mopify/auth/spotify/callback/?code=...

I've seen other similar issues listed here that had been resolved quickly, so hoping this is an easy fix. It's happening for me in both Firefox and Chrome.

Thanks.

**Comment by dirkgroenen** [comment]
That message appears the moment Spotify didn't return a `refresh_token`. There are a few things you can do to help debugging this issue:
- Load in a incognito window and check again;
- Check if the `?code=` is filled with a code;
- Open your Developers Console and check if there's an error in the console.

**Comment by minigopher17** [comment]
Thanks for looking into this.

I've tried in Chrome Incognito and same issue occurred.

URL looks like this: https://bitlabs.nl/mopify/auth/spotify/callback/?code=AQB47kCM8F0qAo5QB2ynjscdnxZl2GbPg3OcIhLJUYYZnLRFHumQM1ZryoBlEzSlZK84Cz4PNmbqBxqO_9FK-OYN1WTKYD0jUDCYbTuM3spRRCowXDpEGahBe3dgZtm9YVHkQJBsXx37ewDO4I0fa1YEWJWJ7lOCVrpZsUVEGkRvQXcYAcQ3pTi1NCb_PvIZM59ZAq_iG820f2ZwmbmyVrmSBVQG8HvuEBmUqR-sHiShrC--1JcJr_Z4tmecljWI23Zi22z0q4GeIhfnn5tomxspi8C3ZS-3bwbLES_awqCtdZtRXuY7UBoq6DyX3wxIECf_DKBJrSbBjwvcv_9smQ

Only thing Developer Console says is: WARNING: Tried to load angular more than once. - mopidy-mopify-1.1.2.js:63577

I'm using Chrome 47.0.2526.73 as well. Have also tried Firefox Developer Edition, both on Mac.

**Comment by minigopher17** [comment]
Downgrading to 1.5.8 fixed the Spotify connect issue. Thanks for your help anyway.

**Comment by dirkgroenen** [comment]
Hmm downgrading helped? I know version 1.5.10 needs a new scope, which results in a new prompt for Spotify to accept those new scopes. Could it be possible you've denied that box or the browser didn't prompt it?

**Comment by minigopher17** [comment]
It successfully asked for new scopes. I think it's possible that the older version didn't upgrade automatically 'mopidy-spotify' to a version >1.4, as I found later versions of 'mopidy-mopify' asks it to upgrade 'mopidy-spotify' to >2.0 and that breaks all Spotify related functionality for me. I'm not too worried about this issue since it's an older version that was affected, and I currently have a nice working version. Thanks!
