### ISSUE TITLE
Support saving playlists offline, just like in regular client

### ISSUE THREAD

**Issue by Cysioland** [dirkgroenen/mopidy-mopify#160]

**Comment by dirkgroenen** [comment]
A bit more information would be nice. How would you like to see this feature work?

**Comment by Cysioland** [comment]
@dirkgroenen I think that would require some cooperation with mopidy-spotify guys. Basically, just like in official Spotify client. You could mark the playlist as offline-saved, and then it would cache the track, in case you run out of internets.

**Comment by dirkgroenen** [comment]
Oh like that, that's a thing for mopidy-spotify indeed. @jodal can probably answer if this is even possible in the libspotify sdk.

**Comment by kingosticks** [comment]
https://github.com/mopidy/mopidy-spotify/issues/10

**Comment by dirkgroenen** [comment]
closing since this is no mopify related issue.
