### ISSUE TITLE
albums should display more metadata

### ISSUE THREAD

**Issue by dnr** [dirkgroenen/mopidy-mopify#163]
When I'm looking through albums from an artist, I'd really love to see some more metadata, especially the number of tracks, total length, and date of release. It's useful to be able to differentiate singles from EPs and full-length albums at a glance, and also useful to see which is an artist's latest release, or second-latest, etc.

At least, this should be on the album page itself. Though I'd love to see some limited info on the artist page or any other page that has a list of albums.

**Comment by dirkgroenen** [comment]
I like your idea and will definitely take this with me. I'm not gonna make any promises about when i'm gonna integrate it, so I'll mark it with 2.0.0 for now.
