### ISSUE TITLE
Add [EXPLICIT] tags next to songs that have explicit lyrics

### ISSUE THREAD

**Issue by KamranMackey** [dirkgroenen/mopidy-mopify#165]
The regular Spotify client does this, so I think Mopify should too.

**Comment by dirkgroenen** [comment]
I don't think I'm able to get the explicit information out of mopidy. On the other hand: I don't really see why adding that label would improve the UX or UI(?).

**Comment by jodal** [comment]
libspotify 12.1.103 added the function `sp_track_has_explicit_lyrics()`. However, this version of libspotify has only been released for the arm6hf architecture, and there has been 2.5 years without any further releases of libspotify. In other words, this functionality is not generally available to pyspotify, thus Mopidy-Spotify, thus Mopidy-Mopify. @dirkgroenen is right.
