### ISSUE TITLE
clicking on items leads to wrong link

### ISSUE THREAD

**Issue by bigmittens** [dirkgroenen/mopidy-mopify#166]
clicking on albums or playlists seems to bring me to a correct page at first (i.e. http://localhost:6680/mopify/#/music/tracklist/spotify:album:4cYtmC2Fp8LKfxUoTAKsIb/Getz-Gilberto) but it will then change the location to mopi**d**y instead of mopify (i.e. http://localhost:6680/mopidy/#/music/tracklist/spotify:album:4cYtmC2Fp8LKfxUoTAKsIb/Getz-Gilberto) for some reason.

**Comment by dirkgroenen** [comment]
Ah, I see. Lemme fix it asap, thanks
