### ISSUE TITLE
Multiple artists are returned as a combined artist string

### ISSUE THREAD

**Issue by 0nse** [dirkgroenen/mopidy-mopify#173]
When listening to songs by multiple artists (e.g. [Nils Frahm — Screws (Reworked)](https://play.spotify.com/album/5cgnmq9bAYVVUWn0TgJ8Aj)), the artist is read as `First artist;Second artist;Third artist;and so on`.

However, this makes my [Last.FM scrobbler](http://mpd.wikia.com/wiki/Client:Mpdscribble) create a whole lot of bogus scrobbles and therefore creates many new artist pages on Last.FM. The scrobbler of Spotify itself will only scrobble the primary artist.

Isn't there a better, dedicated field for additional artists then crunching it all into the main artist tag field? One option would be [#TPE3 Conductor/performer refinement](http://id3.org/id3v2.3.0), which is read e.g. [by ncmpcpp as performer](https://github.com/arybczak/ncmpcpp/blob/c6506d77fd55661c69e626bd19ef5c596e11a0da/src/tags.cpp). Thus, the information would still be accessible, but the main artist would be the primary artist of the release.

Hence, my suggestion is:
* Make TPE1 only contain the primary artist
* Make TPE3 contain any additional artists
  * Separate them using a `/` instead of a `;` as is advised in [ID3v2.0](http://id3.org/id3v2.3.0)
  * If additional information is returned by the Spotify API, consider using TOPE, TPE2 and TPE4 as well

**Comment by dirkgroenen** [comment]
Isn't this issue a Mopidy or Mopidy-lastfm issue? Mopify has no implementations with Last.FM and only reads artist data from Mopidy as it's given.

**Comment by 0nse** [comment]
When it comes to how it is scrobbled, this definitely belongs to the scrobbler.

But I imagined the artist name was retrieved and compiled by mopidy-mopify using the Spotify API. Then, slashes instead of semicolons and using different tag fields would still be relevant to this extension. If this is not the case, you may of course close this ticket immediately.

**Comment by dirkgroenen** [comment]
Nope, most of the track information is coming directly from Mopidy. Mopidy on its behalve is just returning me an array with artists which I'm joining to a string with some links around it. I'm gonna close this one for now as it seems to be unrelated.
