### ISSUE TITLE
Station never gets out of queue

### ISSUE THREAD

**Issue by leotavares** [dirkgroenen/mopidy-mopify#174]
Sorry, couldn't find a better title.

When I start a station, and right after start any music/playlist, the first music of the playlist is played, but right after it, it comes back to the station it was playing before.

The only way I find to "fix" this is to kill mopidy and start it again :(

**Comment by dirkgroenen** [comment]
Ah I see, looks like I've never changed the station behaviour after creating the new queue managed. Thanks for the tip.

**Comment by dirkgroenen** [comment]
Fixed in 1.5.13
