### ISSUE TITLE
No contextmenu in Chromium

### ISSUE THREAD

**Issue by allo-** [dirkgroenen/mopidy-mopify#175]
I do not see how i can add tracks / albums to a playlist. I can create an own playlist, but neither a tracklist seems to have a button on the tracks, nor i see any option inside the created playlist to add music to it.

Is there no support for it, is it hidden somewhere or maybe the interface for it is broken here (latest version from pip, chromium browser)? The wiki says there is support for editing playlists, but does not specify how, either.

**Comment by dirkgroenen** [comment]
You can add tracks by right-clicking on them. There will appear a context menu which contains the Add to playlist option. If this option isn't available you probably have to enable the Spotify service.

**Comment by allo-** [comment]
Sorry, but it's not like i didn't try it.
Right click does nothing at all (example URL for a list: ``http://chimp:6680/mopify/#/music/tracklist/spotify:album:0gRnPYQZZ80mUUJYo1taX4/Sehnsucht``), not even the context menu.

So it seems the interface is broken there.

Version 47.0.2526.80 Built on 8.2, running on Debian 8.2 (64-bit)

**Comment by allo-** [comment]
spotify is connected, adblock does not block anything on the page, cookies are allowed.

**Comment by allo-** [comment]
Hmm, a firefox seems to work. Not sure what the problem is.

**Comment by dirkgroenen** [comment]
Hmm, I have no running instance of Chromium here so I can't check it at the moment. I'll have a look soon to see if it's related to Chromium. I'm using Chrome myself which is working just fine.

**Comment by allo-** [comment]
Sorry, i went through all addons and the mouse gestures addon for chrome interferes with context menus m(. Without it, the menu works as expected.
