### ISSUE TITLE
Sync service doesn't store pushed data [mopidy running as service]

### ISSUE THREAD

**Issue by oboote** [dirkgroenen/mopidy-mopify#176]
Hi guys,

Loving the mopify plugin but haven't some issues getting my credentials to sync across other users in the office. I'm able to authenticate with services and enable Sync on my own browser; I can then "push" and it appears to have worked.

However other browsers aren't pushed the sync details, nor are they able to manually "get" ("No synchronized data available").

I'm running a fresh install of mopidy on raspbian with just a few front-end web extensions.
Mopidy is running as a service under default mopidy setup settings.

The log files indicate the POST is correctly received:
2016-01-11 14:40:02,079 INFO [543:HttpServer] tornado.access: 200 POST /mopify/sync/spotify?access_token=<SNIP>&client_id=<SNIP>&refresh_token=<SNIP> (192.168.1.112) 5.41ms

I suspected it might be related to problems writing to the .config/mopidy-mopify/ folder (stab in the dark from reading https://github.com/dirkgroenen/mopidy-mopify/issues/156), so I chmod -R 777'd the /var/lib/mopidy/.config/ folder with no improvement (that's the home folder listed for "mopidy" in /etc/passwd).

Any ideas where I should look next for what might be interfering? (or if this is a known issue that has been fixed I can just wait for the next update)

Mopidy currently running as a system service so I only get basic logging; next step is to run it manually when it's not being used in the office so try and get some more verbose logging (although currently the logs aren't showing any errors whatsoever).

**Comment by oboote** [comment]
One last thought; it's running on the default port (6680); is a port 80 service hard-coded/expected from the sync tool?

I currently have a basic nginx redirect on 80 which just bounces people over to :6680/mopify/

server {
        listen 80;
        server_name 192.168.1.137;
        return 301 $scheme://$http_host:6680/mopify/;
}

**Comment by dirkgroenen** [comment]
Hmm I have to get into this one, I'll keep you updated.

**Comment by oboote** [comment]
Last suspicion are the warnings mentioned about the "Differences when running as a system service" section of the mopidy docs (http://mopidy.readthedocs.org/en/latest/debian/).

Is there a way to make mopify more verbose in its logging? When playing with sync whilst running mopidy interactively with max verbosity (-vvv), it still only seems to show the websocket messages and then tornado.access GET/POST calls (no errors regarding to writing files which is what I was hoping to find)

**Comment by oboote** [comment]
Okay I've located the issue! (well, one at least :) but I'm afraid my python is virtually non-existent - I don't think I can patch this for you, but perhaps I can provide some info to save you some time)

I noticed the sync.ini file was always empty.

I adding some prints in mopidy-mopify/mopidy_mopify/services/sync/sync.py to see what might be failing. Just after the spotify write() command I added the following and was surprised by the output:

>>        print(self.syncfile)
>>        print(self.syncini)

Output:
None
{u'spotify': {u'access_token': u'<SNIP>', u'client_id': u'<SNIP>', u'refresh_token': u'<SNIP>'}}

I would've expeted self.syncfile to return "/var/lib/mopidy/.config/mopidy-mopify/sync.ini" (which it does during the tests when deciding whether it needs to create the folder).

I therefore hardcoded a self.syncfile = "/var/lib/mopidy/.config/mopidy-mopify/sync.ini" before each time self.syncini is initialised.

My sync.ini now has data, however I still haven't managed to get it all working yet (I'll try and debug some more later/tomorrow). I noticed it's saving client_id's but not tokens (even though when I printed self.syncini previously I was able to see the tokens so I would've expected those to get written).

# cat /var/lib/mopidy/.config/mopidy-mopify/sync.ini
[settings]
forcesync = true
[tasteprofile]
id = <SNIP>
client_id = <SNIP>
[spotify]
access_token = ""
client_id = <SNIP>
refresh_token = ""

**Comment by 0nse** [comment]
I had the same problem. The most recent release fixed it for Spotify (tested between desktop PC and mobile phone). But it still exists for the TasteProfile ID.

**Comment by dirkgroenen** [comment]
You sure you're running the latest version in your browser and restarted Mopidy? I've just tested it and it seems to work fine. Wouldn't make any sense either cause all sync services are the same code wise.

**Comment by 0nse** [comment]
I'm using version 1.5.13 (from the AUR) which to my knowledge is the latest release. Yes, I had restarted Mopidy. That's why it finally started working with Spotify.

Any ideas what I could check for misbehaviour?

**Comment by dirkgroenen** [comment]
Hmm... Not really no to be honest. 

Could you check what (if any) is written in the config file sync uses and if the request results in any errors?

**Comment by 0nse** [comment]
As I'm launching mopidy as its own user "mopidy", `~/.config/mopidy-mopify/sync.ini` remains untouched. Where are the tokens stored instead?

Anyways, since 1.5.14, TasteID is synced as well. Good job! :+1:

**Comment by dirkgroenen** [comment]
Funny, cause 1.5.14 only had some improvements on the QueueManager ;) But glad to hear it's working properly again.
