### ISSUE TITLE
Mopify (dev) doesn't detect Mopidy ?

### ISSUE THREAD

**Issue by timothylhuillier** [dirkgroenen/mopidy-mopify#179]
I installated mopidy on my macbook and I launched grunt watch but I have a already a problem 

http://screencloud.net/v/miVm

Mopidy doesn't detect Mopidy, no ?

**Comment by dirkgroenen** [comment]
Mopidy (by default) runs on port 6680 and Grunt starts on port 8000, so you have to add the correct port number in the settings page.

**Comment by timothylhuillier** [comment]
Oh thanks, I don't thinks that ...

But I have a another problem :( http://screencloud.net/v/wfBo

**Comment by dirkgroenen** [comment]
It looks like the instance of Mopidy which your running doesn't have Mopify installed (?). 

If you want to run the dev branch you have to make sure you tell `pip` to get the Mopidy-Mopify plugin from the git directory. Otherwise you'll be missing some Python code. 

If I'm correct the command should be something like: 
`pip install -e ~/github/mopidy-mopify`

**Comment by timothylhuillier** [comment]
Yes, it's installed and It is running : http://screencloud.net/v/zrel

I'm on api-explorer too : http://screencloud.net/v/yqn9

**Comment by dirkgroenen** [comment]
Oef, what the hell can it be... Let me try to setup the environment to see if/where shit is going wrong. I'll let you know.

**Comment by timothylhuillier** [comment]
What do you want to see exactly ? :)

**Comment by dirkgroenen** [comment]
Ok so I just installed the environment and after settings the port it works out of the box. The steps I executed were: 

- Install Mopidy (`sudo pacman -S mopidy`)
- Install Mopidy-Mopify (`sudo pip install -e /home/dirk/github/mopidy-mopify`)
- `npm install` and `bower install`

- Run mopidy `mopidy`
- Run grunt `grunt watch`

- Go to settings and set port to 6680
- Reload
- Grabbing a :beer:

**Comment by timothylhuillier** [comment]
Me I exectued were :

* I follow these step : https://docs.mopidy.com/en/develop/installation/osx/

* And after, I follow your step in readme :

1. Install Nodejs (v. 5.1)
2. Install grunt-cli and bower: npm install -g grunt-cli bower
3. Clone the repository: git clone git@github.com:dirkgroenen/mopidy-mopify.git on (/Users/tim/Documents/Sites/nodejs/mopidy-mopify)
4. Install dependencies: npm install && bower install
5. grunt watch : http://screencloud.net/v/CR2d

*  launch `mopidy` : http://screencloud.net/v/zrel

* change the port : http://screencloud.net/v/79LG (this screen is after a refresh)

And I don't know why I have this bus. Problem with mopidy ? But api-explore work (and I installed after mopify). But I don't install the spotify extention and I don't modifed my mopidy config

**Comment by dirkgroenen** [comment]
Looking at your steps (and screenshot from the Mopidy terminal) it looks like you haven't executed the pip install? (Step 2 from my previous post).

Does Mopify show up when you go to localhost:6680?

**Comment by timothylhuillier** [comment]
No, I don't use pip but brew.

localhost:6680 : http://screencloud.net/v/Fdu4

**Comment by dirkgroenen** [comment]
Correct. The grunt process only makes the webinterface available. You still need to install and run Mopidy separately. 

Normally you don't have to install the frontend separately, but since Mopify has some extra extensions which only run in Mopidy, you have to make sure it's installed too.

**Comment by timothylhuillier** [comment]
Oki thanks for explication.

I would like to interact wirh my Phillips hue for you, I must create a backend/frontend extention or create directly the interaction with mopify and nodejs package (or angular package)

Thanks

**Comment by dirkgroenen** [comment]
How do you want the Hue to interact with Mopidy?

**Comment by timothylhuillier** [comment]
Synchronise my hue with the song
Le 28 janv. 2016 11:13 AM, "Dirk Groenen" <notifications@github.com> a
écrit :

**Comment by dirkgroenen** [comment]
In that case you probably don't need to do anything with Mopify (unless you want to add a settings page for example which controls the Hue light).

I would suggest creating a [FrontendExtension](http://mopidy.readthedocs.org/en/latest/extensiondev/) which handles the communication with your Hue. If you somewhere to start you can take a look at the Mopidy documentation, or at the QueueManger frontend extension I've added to Mopify.

**Comment by timothylhuillier** [comment]
Oki Thank you, for explication.

QueueManger is frontend extention dev yourself, right ?

Thanks

**Comment by dirkgroenen** [comment]
Correct

**Comment by timothylhuillier** [comment]
How uninstall that `sudo pip install -e /Users/tim/Documents/Sites/nodejs/mopidy-mopify` :D

I would like to install the officiel package too and I have this error

`Not uninstalling mopidy-mopify at /Users/tim/Documents/Sites/nodejs/mopidy-mopify, outside environment /Users/tim/code/.virtualenvs/mopid`

**Comment by dirkgroenen** [comment]
You should be able to remove it by uninstalling by the package's name. So `pip uninstall mopidy-mopify`.

**Comment by timothylhuillier** [comment]
I have this message when I do `pip uninstall Mopidy-Mopify`

    sudo pip uninstall mopidy-mopify
    Password:
    The directory '/Users/tim/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
    Can't uninstall 'Mopidy-Mopify'. No files were found to uninstall.

and when I do `pip uninstall /Users/tim/Documents/Sites/nodejs/mopidy-mopify`
I have nothing.

**Comment by dirkgroenen** [comment]
Hmm though one. Could it have something to do with different virtual environments?
