### ISSUE TITLE
Change the behavior of the search function

### ISSUE THREAD

**Issue by dirkgroenen** [dirkgroenen/mopidy-mopify#18]
At the moment the search function is a bit to simple and lets the user click more often than it should do. I'm thinking if changing this function to something a bit more like MySpace where the results popup directly (fullscreen) when you start typing. Only the way how the results are being displayed has to be somewhat else than how MySpace does it.

MySpace:
![](http://i.imgur.com/VZZ9TGW.png)

**Comment by hkultraman** [comment]
Any target release date on 1.5.0? thx

**Comment by dirkgroenen** [comment]
Tim testing it at the moment, if everything works well I expect it to be released withing the next few days.

If you can wait you can also download Mopidy from the development branch, I've packaged 1.5.0 yesterday so you should be able to install it.

**Comment by hkultraman** [comment]
Great, I will wait for your release then. Any screenshot? Cheers.

**Comment by dirkgroenen** [comment]
Screenshots are in the development branch's readme

**Comment by hkultraman** [comment]
Cool, thx
