### ISSUE TITLE
Copy Spotify URI / Copy HTTP Link don't work in Safari

### ISSUE THREAD

**Issue by elsurudo** [dirkgroenen/mopidy-mopify#180]
Tested in Safari 9.0.3 (OSX Yosemite 10.10.5)

**Comment by dirkgroenen** [comment]
The implementation makes use of [Clipboard.js](https://clipboardjs.com/) which is, unfortunately, not supported on Safari.

**Comment by elsurudo** [comment]
That's a shame. Any ideas on an implementation that would gracefully degrade for Safari users? Right now, it just fails silently.

Perhaps showing the link inline in the menu, and "selecting" it, with a tooltip to press command-C to copy for Safari users? This is similar to the Clipboard.js graceful degradation

**Comment by dirkgroenen** [comment]
Something like that may work, let me give it a try.
