### ISSUE TITLE
apple-touch-icon.png

### ISSUE THREAD

**Issue by karlvr** [dirkgroenen/mopidy-mopify#182]
Mopify works great when saved to the home screen on an iPhone or iPad, however the icon is automatically generated. Would you consider creating an `apple-touch-icon.png` and including the appropriate meta tag on each page? See https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html

Thank you very much for this excellent software!

**Comment by dirkgroenen** [comment]
I've added it in the dev branch. The issue will close when I'm rolling out the new version which contains the fix.

**Comment by karlvr** [comment]
Thank you! Champion.
