### ISSUE TITLE
Make tabname change optional

### ISSUE THREAD

**Issue by d3rrial** [dirkgroenen/mopidy-mopify#183]
Just a suggestion, not a bug:
When the song changes, so does the name of the tab. If you're using chrome and have the tab pinned, the tab will madly blink every couple of minutes when the song changes and you have to click on the tab and click away again.
It's probably not an issue for most people, it is only a slight annoyance after all, but it's something to think about.

**Comment by dirkgroenen** [comment]
Haha, I indeed noticed that too a while a go but never marked it as an annoying thing. I might add a checkbox or something in the settings page to disable the behavior.

**Comment by dirkgroenen** [comment]
Just released a new version with an extra toggle on the settings page to disable this.
