### ISSUE TITLE
Add to queue unavailble on touch screen

### ISSUE THREAD

**Issue by sebgre** [dirkgroenen/mopidy-mopify#184]
Hi,
I'm just discovering mopidy-mopify. Great work !
Only concern I have is that it is not possible (or I don't have found it) to use "add to queue" with a touchscreen. You need to use the right click for that, but this is not available on a Raspberry Pi like setup with only a touchscreen and no mouse. 
Thanks

**Comment by dirkgroenen** [comment]
Normally a long press results in the same event as a right click. At least it does on android and ios.
