### ISSUE TITLE
Use the me/albums and me/following API endpoints to fetch the saved albums and artists

### ISSUE THREAD

**Issue by gontanon** [dirkgroenen/mopidy-mopify#186]
This comes from a issue report I just opened and closed in mopidy-spotify:

https://github.com/mopidy/mopidy-spotify/issues/101

Summarising: I'm seeing very slow and unreliable (incomplete lists that don't reload) behaviour in the Artists and Album views and I think it is because these views are being generated by loading my entire list of saved tracks over HTTP requests of 50 tracks at a time. On a Library of thousands of tracks, I can see how this could be a problem.

The Spotify HTTP API offers endpoints to fetch these directly, wouldn't these views load much faster using those?

**Comment by gontanon** [comment]
Patch: https://github.com/dirkgroenen/mopidy-mopify/pull/188

**Comment by dirkgroenen** [comment]
Added in 1.5.17
