### ISSUE TITLE
Browse the full Spotify "Featured playlists" (Genres & Mood, etc.)

### ISSUE THREAD

**Issue by oboote** [dirkgroenen/mopidy-mopify#187]
The Genres & Mood playlists (similar to the Featured playlists but not time-dependent) are a great selection of set-and-forget playlists; any chance of browsing and loading these in mopify?

I accept this is an enhancement and not a bug fix - as and when you have the time to take a look. In the mean time I'll see if I can identify the timezone issues which would make featured playlists more relevant.

**Comment by gontanon** [comment]
See https://github.com/dirkgroenen/mopidy-mopify/pull/188

**Comment by dirkgroenen** [comment]
I'll keep this one open but for now I'm not going to do anything with it. My spare time is limited and for now I want to focus on the recreation of Mopify, which will probably include this enhancement too.
