### ISSUE TITLE
album is removed from search when removed albums

### ISSUE THREAD

**Issue by bigmittens** [dirkgroenen/mopidy-mopify#189]
when searching for an album, if the album is saved and you right click > remove album, the album will be removed from the search query as well.

**Comment by dirkgroenen** [comment]
Hmm makes sense, I'll keep this one open but for now I'm not going to do anything about it. Changing this would require some changes in the general structure of the code. My spare time is limited and for now I want to focus on the recreation of Mopify. 

If I at some point have to make changes to this 'structure' I'll keep this issue in mind.

**Comment by bigmittens** [comment]
yeah, i get that. it's not really a big deal at all, just making sure you're aware.

**Comment by dirkgroenen** [comment]
I wasn't, but I'm now. ;)
