### ISSUE TITLE
albums not showing up after upgrading to 1.5.17

### ISSUE THREAD

**Issue by bigmittens** [dirkgroenen/mopidy-mopify#192]
After upgrading to 1.5.17 going to "Albums" under "Your Music" strangely only shows 7 of the 100+ albums I have saved. Reverting to 1.5.16 fixes the issue.

**Comment by dirkgroenen** [comment]
What does Spotify's client show you? 1.5.17 Uses the new official endpoint from Spotify which should return the same amount of albums as the Spotify client does. The previous version used a 'hack' to get the albums.

**Comment by bigmittens** [comment]
[Here's is the albums page now.](https://cloud.githubusercontent.com/assets/2244606/14338707/f865eae6-fc2d-11e5-988c-d644f3b7c35f.png)

[This is a (large) screenshot I took a while ago of all of the albums.](https://cloud.githubusercontent.com/assets/2244606/14338737/22dd9efe-fc2e-11e5-8f26-68012e541d0e.png)

**Comment by dirkgroenen** [comment]
Yeah ok, but that doesn't answer the question I asked ;)

**Comment by bigmittens** [comment]
Oh, the official client. Sorry. It shows all the albums.

**Comment by runnerway** [comment]
Same problem here. ALBUMS and ARTISTS empty with 1.5.17. 
Going back to 1.5.16 solves the problem.
(But obviously doing so we lose all the benefits of new official endpoints..)

:)

**Comment by dirkgroenen** [comment]
Have you guys tried reloading the Spotify tokens? (Services > Spotify > Reconnect)

**Comment by bigmittens** [comment]
Just tried it, no luck.

**Comment by dirkgroenen** [comment]
Ok, in that case I'm interested in the requests being made. Could you paste a screenshot of your developer tool's network tab after a page reload?

**Comment by dirkgroenen** [comment]
Just noticed the Spotify endpoint only returns albums you follow, where the previous function (and spotify's official client) also return albums from songs you've added to your library.

Is this the case here too?

**Comment by bigmittens** [comment]
No. I've no clue why the albums that do show up are there, but every one of the old albums had been saved individually. I don't usually save songs, I just add them to playlists (none of the albums shown now are in any playlists).

**Comment by dirkgroenen** [comment]
Ok last thing I would like you to test to try and solve this issue for you. Can you check the output of Spotifys API request through the API explorer and see if that one returns more correct date? 

Link to endpoint is https://developer.spotify.com/web-api/console/get-current-user-saved-albums/?limit=50

**Comment by bigmittens** [comment]
Date: Sun, 12 Jun 2016 22:58:25 GMT
Is this what you mean?
The date and time is correct.

**Comment by bigmittens** [comment]
Also, looking at the response box, the albums are the same.

**Comment by dirkgroenen** [comment]
No I meant the response you got. The fact you're saying the albums are the same means that unfortunately there's nothing I can do.

As previously explained the old code used your saved songs to generate the albums. The new code use the official Spotify API endpoint to get your saved songs.

**Comment by bigmittens** [comment]
Hmm. Does the mobile application use this endpoint? The mobile application correctly returns the albums like before. Maybe it has to do with the request?

**Comment by bigmittens** [comment]
I've found the albums shown after the update are the one's saved on mobile, while the ones no longer shown are the ones saved on mopify.

Saving albums through mopify after the update also doesn't add them to the library.
