### ISSUE TITLE
Playlist "Discover weekly" isn't updating.

### ISSUE THREAD

**Issue by mathieuhays** [dirkgroenen/mopidy-mopify#194]
Hi, 

Thanks for the awesome player :)

I've had an issue where the "Discover weekly" playlist (which changes every monday) is not updated in Mopify.

I managed to clear the cache by restarting Mopidy's service but that's a bit overkill.

Is that fixable ? If it isn't we could have an option where we could force load the playlist from Spotify.

Thanks,

**Comment by dirkgroenen** [comment]
Hmm I've never heard of seen this before and if it happens it's definitely not something which happens in mopify. Each time you open a playlist it gets fresh data from Mopidy, so if you're getting the same playlist over and over again you might want to open an issue in Mopidy or Mopidy-Spotify.

**Comment by mathieuhays** [comment]
Makes sense.
Thanks
