### ISSUE TITLE
Playlist folders with "/" cause bugs in display of playlists inside them

### ISSUE THREAD

**Issue by oboote** [dirkgroenen/mopidy-mopify#195]
Hi,

Reporting this for the sake of it but the fix from the user point of view was easy: change "EDM/Dance" to "EDM-Dance".

If a folder of playlists has a / in it, all playlists inside it will have the part after the slash as their name.

IE my folder is called "EDM/Dance", all the playlists inside were displayed with a name of "Dance". Renamed the folder to remove the / fixed it.

**Comment by dirkgroenen** [comment]
Unfortunately I can't do anything about this. This 'bug' has come around a few times and the solution ain't in my hands. Using the Spotify library I can only divide playlists into directories by using the `/`. So to solve this issue changed have to be made in the Spotify library.
