### ISSUE TITLE
Port isn't reset to default value when clearing

### ISSUE THREAD

**Issue by ndbroadbent** [dirkgroenen/mopidy-mopify#198]
I cleared the `mopidy port` field, and expected it to be reset to the default value of `6680`. Instead, the websocket requests were now being sent to port 80 by default.

I think the default behaviour should be to reset the port to `6680` if a value is entered and then deleted.

**Comment by dirkgroenen** [comment]
The default port isn't set to `6680`, but to the port you're using to visit Mopify with. There have been a few discussions around this subject and eventually we've decided to use this behavior.
