### ISSUE TITLE
No obvious way to 'save to your music' from mopify

### ISSUE THREAD

**Issue by grgcnnr** [dirkgroenen/mopidy-mopify#201]
This might be by design & apologies if I have missed something here but it confused the heck out of me for some time.

Saving an album in mopify is the equivalent to hitting save in the Spotify app. Currently there is no obvious way to add an album to "Your Music" => "Albums".

This would be super useful.

**Comment by dirkgroenen** [comment]
At the album page there is a button on the right side. Using this button you can save or remove albums from your collection.

![image](https://cloud.githubusercontent.com/assets/1001391/17264961/205f0e62-55eb-11e6-8ac1-360ee6618116.png)

**Comment by grgcnnr** [comment]
Apologies, let me explain a bit better :)

When you save an album in mopify:

<img width="600" alt="1" src="https://cloud.githubusercontent.com/assets/2694014/17267297/894aa7f6-5659-11e6-8c4a-e09d61a61c59.png">

It appears in your songs list:

<img width="600" alt="2" src="https://cloud.githubusercontent.com/assets/2694014/17267302/a01ade9c-5659-11e6-9301-c54aa9aaaa3c.png">


But not in your albums:

<img width="600" src="https://cloud.githubusercontent.com/assets/2694014/17267271/02b84464-5659-11e6-857c-0b9e2927b72e.png" >


This is kind of how spotify works too, you have to go to albums and "**Save to your music**":

<img width="454" alt="4" src="https://cloud.githubusercontent.com/assets/2694014/17267314/c1bdbd58-5659-11e6-896f-f54639d084e3.png">


After that, it will appear in Mopify's album list:

<img width="600" alt="5" src="https://cloud.githubusercontent.com/assets/2694014/17267318/d5b40ba0-5659-11e6-8a4b-ae4cc1232382.png">


So I guess my question / issue is 2 part:

1. Is this the expected behaviour?
2. If so, how do you add albums to the "Albums" page from within Mopify?


Thanks for all your amazing work on this by the way @dirkgroenen it's fantastic work!

**Comment by dirkgroenen** [comment]
Ah I see what you mean. Just tested it and it appears we've forgot to change the add album/artist endpoints to the new ones which are used by the My Collection pages.

A few versions ago Spotify didn't have direct 'Save album/artist' endpoints, so we just saved all tracks and grouped them on the album page. Now we have changes the artist and album endpoint, but didn't change those buttons.

Thanks for the tip, I'll take this with me the next time I'm working on it.
