### ISSUE TITLE
Removing songs from playlists is tedious

### ISSUE THREAD

**Issue by gumb00** [dirkgroenen/mopidy-mopify#202]
This has been bugging me for quite a while now..
After selecting multiple songs from a playlist I am able to move them to another playlist. However I am not able to find a way to delete multiple songs with one click (only the song with the mouse hovering over it gets removed).
Also there is not keyboard shortcut (e.g. `del`) to remove songs in a fast manner.

**Comment by dirkgroenen** [comment]
Hmm, the code should support removing multiple tracks. You're saying the item doesn't appear in the context menu when you have multiple tracks selected?

**Comment by gumb00** [comment]
I can see the option in the context menu but it only removes one song in the playlist instead of all those I selected. The song removed is the one that I right clicked on to open the context menu.
