### ISSUE TITLE
Spotify Authentication Failing

### ISSUE THREAD

**Issue by Prime624** [dirkgroenen/mopidy-mopify#204]
Finally got it connected to Spotify and now it displays my playlists, albums, etc. When I click on an album or playlist however, it begins trying to load the info but never completes. When I click play from the album page, it flashes the "loading tracks" at the bottom but a second later it just says connected again without playing anything. I'm using it on an RPi 3 from my Ubuntu laptop with Chrome.

When I check the status of mopidy on the pi, it says
`INFO      Failed to lookup "spotify:album:0ETFjACtuP2ADo6LFhL6HN": Session must be logged in and online to load objects: <ConnectionState.LOGGED_OUT: 0>`

Any idea what's wrong or how to fix this?

**Comment by charli-polo** [comment]
I have the very same issue.

**Comment by dirkgroenen** [comment]
Sounds like you haven't logged in in Spotify in your Mopidy client. Mopify and Mopidy both require independent spotify sessions. Please fill in your config file as described on the Spotify repo https://github.com/mopidy/mopidy-spotify.
