### ISSUE TITLE
Improve navigation for Mopify running on Chrome as an app

### ISSUE THREAD

**Issue by epassaro** [dirkgroenen/mopidy-mopify#205]
Launching mopify as an app on Chrome makes navigation a bit complicated.
For example this action can't be done: search, pick and album, go back to search results.

**Comment by dirkgroenen** [comment]
Why is that action unavailable? Opening the site in a Chrome app is just the same as opening the site in your mobile browser. I've personally been using the app as Chrome app since the start and never recognized any unexpected non-behave.
