### ISSUE TITLE
Unable to connect to Spotify OAuth

### ISSUE THREAD

**Issue by coldfumonkeh** [dirkgroenen/mopidy-mopify#210]
I've just installed PiMusicBox 0.6.0 and am unable to authenticate my Spotify account within Mopify bundled with MusicBox.

After logging in via the pop-up:

```
Something went wrong...

Looks like Spotify didn't return the correct tokens. Please close this window and refresh Mopify.

invalid_grant: Invalid redirect URI
```

Is there an issue with the Bitlab.nl redirect domain? Has anyone else experienced this?

Many thanks

**Comment by kingosticks** [comment]
I don't know if mopify still works on pimusicbox since it uses a very old
version. I'm afraid I cannot test it myself as I am currently away.

**Comment by dirkgroenen** [comment]
I don't know which version of mopify MusicBox has bundled, but it sounds like something is going wrong with the given bitlabs url. Can you please copy and paste the full url of the window so I can check what has been appended?

**Comment by coldfumonkeh** [comment]
Thank you @kingosticks and @dirkgroenen (and a belated Merry Christmas to you both).

The URL for the auth process is:

`https://bitlabs.nl/mopify/auth/spotify/callback/?code=AQDV0-IO71XqbM5VrD4XkgWZsiPIL6zw0kbWXwSxd6jIZwqn0VnBpLMHi7nHCnNG-JZ2FPHg6AMnlMV9ZcZovqdnVAXuRIWVsLTDYNbA3yleZNID2CGqQkJY7kFKMGeY170JH7woLlTQsDoS6eolq9jMVlMMovY38TypXV_80V17FUdBPudleF2mkOjWQGA6H0PKR8CgSzXklgZ-pYjrWVZ70w4-F0tXSyXHPNLqQEWj4d_n49UNIFfDxwP7Aj-LSoTABbWZr3e22GFqE-wWDUBNnUt25-LuILDWud69vNUz9PmcUij6DxM296HiIJdIrJ3iR6Z7O1d8uF3AUjGzvQ`

**Comment by dirkgroenen** [comment]
Thanks @coldfumonkeh, likewise. I've just installed the latest version of mopidy-mopify (no musicbox) and everything works fine. Could you check the version you're running? It's listed on the settings page.

**Comment by coldfumonkeh** [comment]
@dirkgroenen It's running a shockingly retro 1.1.2. I tried updating it yesterday to the latest version but it blitzed the entire HTTP server so nothing was available via the web interface.

**Comment by dirkgroenen** [comment]
Auch, 1.1.2... I would strongly suggest you to update to a newer version. If you're not using any of musicbox's features you could always reinstall/update mopidy and mopify separately.

**Comment by coldfumonkeh** [comment]
I'm going to create a separate mopidy / mopify Pi box I think. I still use some of the MusicBox features so will raise that issue with the correct repo team as they need to pull it together with the latest awesomeness. Many thanks!

**Comment by dirkgroenen** [comment]
Alright no problem, good luck!
