### ISSUE TITLE
Install without sudo on OS X

### ISSUE THREAD

**Issue by rnkn** [dirkgroenen/mopidy-mopify#211]
Could you please provide some guidance for how to install without `sudo` for users without administrator access or those who want to keep their system consistent?

I'm on a Mac, so for me, adding to https://github.com/mopidy/homebrew-mopidy would be quite very helpful.

**Comment by rnkn** [comment]
Figured it out...

~~~
$ curl -O https://bootstrap.pypa.io/get-pip.py
$ python get-pip.py --user
$ echo "${HOME}/Library/Python/2.7/bin:$PATH" >> ~/.bashrc
$ source ~/.bashrc
$ brew install mopidy
$ echo 'import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")' >> ${HOME}/Library/Python/2.7/lib/python/site-packages/homebrew.pth
$ pip install --user mopidy-mopify
~~~

It's a bit complicated for the average user so might be worth adding this to the README?

**Comment by dirkgroenen** [comment]
I work on Linux so I cant test or confirm it, but I'll add a link referring to this thread to the README for people interested in installing it on OS X without sudo. Thanks.

**Comment by rnkn** [comment]
Not sure if it's the canonical way to do it... This was just a bunch of trial and error...

**Comment by dirkgroenen** [comment]
Others can always drop their opinion over here. If this is indeed not the appropriate way we can always change it or remove the link.
