### ISSUE TITLE
Log played tracks into a history (or syslog)

### ISSUE THREAD

**Issue by fekete-robert** [dirkgroenen/mopidy-mopify#213]
Hi, 

First of all, thanks a lot for this excellent player!

Is there a relatively easy way to send information about the played tracks (title, artist, album, playlist if exists, and so on) into syslog? I'd like to collect the history into a database, and I'd know how to do it once it gets into a log message.

Thanks!

**Comment by dirkgroenen** [comment]
Closing this cause it's irrelevant to mopidy-mopify. Though to help you forward:

Develop a mopidy extension which hooks onto the frontend `track_playback_started` event and stores information in your database (or direct it to your syslog, but why not directly add it in your db).

https://docs.mopidy.com/en/latest/api/core/?highlight=track_playback_ended#mopidy.core.CoreListener.track_playback_started

**Comment by fekete-robert** [comment]
Thanks a lot for the pointer!
