### ISSUE TITLE
Playback fails after a few songs and/or bugs out

### ISSUE THREAD

**Issue by costpermille** [dirkgroenen/mopidy-mopify#215]
After track 1: ![thw](https://cloud.githubusercontent.com/assets/19752699/22622011/51caa026-eae5-11e6-9f34-e1da058871e4.png)

Song is 4:11 long then starts playing next track, when it starts playing the next track the title doesn't update and the timer continues going on offscreen, creating scroll bars. When track after this ends, mopidy stops playing.

After track 2: ![image](https://cloud.githubusercontent.com/assets/19752699/22622034/c6ec33d8-eae5-11e6-9e09-91f952001360.png) (the bar still ticks up, but nothing is audible anymore)

Should be on latest versions on pip/apt, installed via the apt.mopidy repo.

**Comment by dirkgroenen** [comment]
The failing playback is something on Mopidy's side, that said: the seekbar continuing out of its borders is indeed a bug in the UI.
