### ISSUE TITLE
htaccess/passwd

### ISSUE THREAD

**Issue by blackjack4494** [dirkgroenen/mopidy-mopify#217]
Hey, is there any easy solution for using/setting up some authentication? I tried creating htaccess and htpasswd here: /usr/local/lib/python2.7/dist-packages/mopidy_mopify/static/debug/src/app
But I guess it is just being ignored. Anyway I am not even sure if it starts the app in this folder :D

**Comment by vvasabi** [comment]
`.htaccess` is an Apache httpd technology. I don’t believe Mopidy or Mopify would have anything that can support `.htaccess`.

That said, you can set up a reverse proxy with httpd, so Mopidy would be served via httpd and `.htaccess` rules can work. For more info, look up httpd’s `ProxyPass` directive or the `P` flag of `RewriteRule`.

**Comment by dirkgroenen** [comment]
Exactly what @vvasabi said. Mopidy uses Python's Tornado browser, so you won't be able to use `.htaccess`.
