### ISSUE TITLE
Unable to lookup any playlist

### ISSUE THREAD

**Issue by dangerjosh** [dirkgroenen/mopidy-mopify#218]
I am unable to look up any playlist, be it the user I am logged in as or another user's playlist...or a Spotify playlist like the "New Music Friday". I get errors like:

Failed to lookup "spotify:user:dangerjoshmusic:playlist:19DjCNeU0bsJQRaXNHTAut": Operation did not complete in 10.000s

I found this: https://github.com/mopidy/mopidy-spotify/issues/71

but that was 2015, and I wasn't sure if I should try it with the newest version I just installed today...

**Comment by dirkgroenen** [comment]
I would suggest to check your versions and make sure everything is up-tp-date. Please open an issue in mopidy-spotify If you stil experience issues afterwards, this seems to be unrelated to Mopidy-Mopify.
