### ISSUE TITLE
Please connect with the Spotify service first

### ISSUE THREAD

**Issue by huntersmith18** [dirkgroenen/mopidy-mopify#219]
Hi I am new to the program I was using iris and it worked pretty good but I like the look of mopify better but every time I click on anything it says please connect with the Spotify service first I looked in my mopidy config and it is logging into my Spotify but can't get it to work in mopify any help would be appreciated I am using an rpi3 with touch screen

**Comment by huntersmith18** [comment]
Ok to clarify it seems to only happen when I select anything under the discover tab

**Comment by huntersmith18** [comment]
Ok one more update the more I mess with it sometimes it says enable the Spotify service to use this feature is there a way to enable Spotify as a service I'm sorry if my questions arnt giving you the information needed I am really new to this

**Comment by huntersmith18** [comment]
It seems to do it more when I am running mopidy as a service at boot but when I I start it manually it seems to work better

**Comment by dirkgroenen** [comment]
With Spotify Service we're referring to the Spotify service located in Services (located in the menu). Enable the Spotify service and connect your account to reveal more features like the discover page.
