### ISSUE TITLE
Automatic updating 

### ISSUE THREAD

**Issue by dirkgroenen** [dirkgroenen/mopidy-mopify#22]
Let Mopify automatically update itself. Should be possible with the ```tornado.web request handler``` and ```pip update```. 

Worth trying..

**Comment by dirkgroenen** [comment]
Added in next release ([1.4.0](https://github.com/dirkgroenen/mopidy-mopify/milestones/1.4.0))

**Comment by kingosticks** [comment]
Cool! I wanted something like this in mopidy-websettings.

**Comment by dirkgroenen** [comment]
Must say that it still isn't perfect since I haven't found a way to restart Mopidy after updating, but for now it's a nice gimmick.

**Comment by kingosticks** [comment]
There's some hack in websettings for restarting it when you're just running
it in the terminal but it doesn't work when it's a service. I played around
it before but lost interest. Will post back if we do find a nice solution.

**Comment by dirkgroenen** [comment]
Yes I've seen that hack, but I don't want to restart the whole system after updating. At the moment a reboot isn't always necessary. It depends on the changes made in Mopify.  When changes have been made in the python core files a reboot is needed, but when only html, js and css files have been updates it isn't required.

**Comment by kingosticks** [comment]
There should be another (!) hack, maybe commented out, that just reloads
the python process rather than the whole system. And Yeh, a reboot is
complete overkill most of the time but I think getting something working
was the idea at the time.

**Comment by dirkgroenen** [comment]
I have been experimenting with restarting the process, but I haven't been able to do this successfully. The biggest problem I encountered was the process being killed (duh) which disables the ability to start a new process.

In the meantime I've created a new issue #87 where we can discuss further improvements to this feature.
