### ISSUE TITLE
Artist Pages don't load

### ISSUE THREAD

**Issue by BLX-S** [dirkgroenen/mopidy-mopify#225]
As the title says: the artist pages don't load... I don't know which logs to provide to aid development but I'd be glad to help reproduce it.

**Comment by tobiasstrebitzer** [comment]
I've had this issue as well. I've created a pull-request to resolve this: #227

To try this package, install via:
```bash
sudo pip install https://github.com/tobiasstrebitzer/mopidy-mopify/raw/bugfix-update-dependencies/dist/Mopidy-Mopify-1.6.0.tar.gz
```

You might need to uninstall any existing version before:
```bash
sudo pip uninstall Mopidy-Mopify
```
