### ISSUE TITLE
Suggested playlists loading slow

### ISSUE THREAD

**Issue by BLX-S** [dirkgroenen/mopidy-mopify#226]
The highlighted playlists on the home page don't load. When I click play it hangs indefinitely on loading tracks and when I try to load the list GUI it also loads forever. I don't know if this is correlated with the recent Spotify API troubles...

BTW My personal playlists load fine. It might be a size issue?

**Comment by tobiasstrebitzer** [comment]
I've notice this too... it seems like foreign playlists aren't loading.

**Dev-Note:**
The responsible controller tries to load the playlist tracks, but receives an empty result:
* [src/app/music/tracklist/tracklist.controller.js line 171](https://github.com/dirkgroenen/mopidy-mopify/blob/b102f96acf4fc08ccfca3b0214b4d90a9b17eb02/src/app/music/tracklist/tracklist.controller.js#L171)
