### ISSUE TITLE
About connecting to Spotify

### ISSUE THREAD

**Issue by sarukuku** [dirkgroenen/mopidy-mopify#23]
Can Mopify be configured in a way that it would automatically use the Spotify credentials provided by the mopidy-spotify in the Mopidy user config? What about the other settings?

We are using Mopify as a shared service in our office and it would be quite frustrating to go through every user and reconfigure all the settings and reconnect the Spotify account for each of them.

The client we like, it looks good :+1:

**Comment by dirkgroenen** [comment]
I will look into that. Not sure if it's possible to get the settings of an other extension.

**Comment by sarukuku** [comment]
Great! From my point of view it's not in any way meaningful to try to fetch them from the Mopidy config if that is hard / impossible. As long as you could just put them in some config and the app would automatically use them to connect to Spotify and populate the settings. Something like below in the Mopidy config perhaps.

 ```
[mopify]
enabled = true
spotify_username = asd123
spotify_password = asd123
ip_address = 127.0.0.1
port = 6680
language_code =
country_code =
```

**Comment by dirkgroenen** [comment]
Ofcourse that's also possible, but personally I would prefer to fetch them from the Spotify config. If that ain't possible I'll add them to the Mopify config.

**Comment by sarukuku** [comment]
Sounds good to me :+1:

**Comment by dirkgroenen** [comment]
Looks like logging in the user is going to be a bit harder than expected. This idea will be moved a bit lower on the priority list for now.

**Comment by tindzk** [comment]
According to https://developer.spotify.com/web-api/authorization-guide/, this cannot be implemented solely on the basis of user/password credentials. I'm accessing the Mopify user interface from a couple of computers and have to log in with each of them individually (same for 'Taste Profile'). The referenced website mentions a possible solution:

> You could implement an app where you logged in using the 'Authorization Code' flow. Then, store the obtained access token and refresh token. Use the access token to perform the requests, and renew the access token whenever it expires using the refresh token.

**Comment by dirkgroenen** [comment]
At the moment the Spotify authorization process goes via an extra server which makes it possible to use a refresh_token. 

At the moment the only idea I have is to store the tokens somewhere in Mopidy and retrieve them from another client. This means that the user has to login in one of the Mopify clients which will store the tokens all the other computers use. 

This idea really needs some good thinking since we're bypassing Spotify's default authorization possibilities.

**Comment by dirkgroenen** [comment]
At the moment I'm developing this feature as a Service (Sync). The Sync service will enable you to synchronize data with other Mopify clients that are using the same Mopidy server.

I would like to hear from you how you would like to see this Spotify synchronization. The idea behind the sync is that the access and refresh tokens are saved on the Mopidy server (in your own network) and that other clients can retrieve those tokens and use them to do requests.

**Comment by sarukuku** [comment]
Sounds good to me. It would solve the problem why I opened this ticket in the first place so I'm happy with what ever works. :+1:

If you want some reference on how others have done it check the [Mopidy Spotify] (https://github.com/mopidy/mopidy-spotify) and the [MusicBox Webclient] (https://github.com/woutervanwijk/Mopidy-MusicBox-Webclient). The webclient works by utilizing Mopidy Spotify and the Mopidy Spotify fetches the Spotify credentials from the Mopidy configuration. The web interface basically controls the Mopidy Spotify service running on the server and the result is a shared Spotify client that a group of people can control via the web interface.

Your architecture might not easily fit to this kind of patter so it's ofc. up to you how to best achieve this but that's one way to do it.

**Comment by dirkgroenen** [comment]
There is one big problem why it can't be done easily: the difference between the authentication flow. 

To extend Mopify with extra Spotify features (and let Mopidy do less work) I have used the Spotify Web API. The Web API doesn't use the same authentication flow as the libspotify library which gives me the problem that I can't use the provided spotify credentials in the config file. Sadly (for us) Spotify has protected their login form with a  CFRS token, so I can't inject the credentials.

I'm currently testing the Sync method I described yesterday and it's working pretty good. It even gives us the opportunity to sync the other services like Taste Profile.

I hope to release it within the next few days, or maybe even tonight. 

Little sneak peak of how it's going to look:

![http://i.imgur.com/B1BpQW2.png](http://i.imgur.com/B1BpQW2.png)

**Comment by dirkgroenen** [comment]
I've added the Sync service in 1.3.1 which I've just released.

I've only been able to test it on my own computer with an extra incognito window, so I would like to hear how its working for you. I'm new in writing in Python, so please take a look at your mopidy process and see if it doesn't create any errors. If it does; let me know so I can look into it.

**Comment by sarukuku** [comment]
Good work :+1: I'll try to find time to update our office system this week and report back how this new feature works in our environment.

**Comment by sarukuku** [comment]
Ok, so we installed the update yesterday and things seem to be working as expected. Good work! :+1:

**Comment by dirkgroenen** [comment]
Good to hear! Let me know if something ain't working properly or if you have a good idea.
