### ISSUE TITLE
Playlists and Search: TypeError: Cannot read property 'toLowerCase' of null

### ISSUE THREAD

**Issue by mstruebing** [dirkgroenen/mopidy-mopify#230]
When I open the Playlist tab on mopify or do a search I get the following error: `TypeError: Cannot read property 'toLowerCase' of null`

I'm using:
Mopidy (2.1.0)                                                                                                                                                                                                      
Mopidy-Mopify (1.6.1)                                                                                                                                                                                               
Mopidy-Spotify (3.1.0)                                                                                                                                                                                              
Mopidy-Spotify-Tunigo (1.0.0)  

In the network tab of my Browser I see a request for example https://api.spotify.com/v1/search?limit=50&market=US&q=black+sabbath&type=album,artist,playlist when searching for 'black sabbath' outgoing which return valid looking json.

In case of playlists it does a request to: https://api.spotify.com/v1/users/username/playlists?limit=50
where I also get valid looking json. 

This is one example entry of the search json:

```
{
  "albums" : {
    "href" : "https://api.spotify.com/v1/search?query=black+sabbath&type=album&market=US&offset=0&limit=50",
    "items" : [ {
      "album_type" : "album",
      "artists" : [ {
        "external_urls" : {
          "spotify" : "https://open.spotify.com/artist/5M52tdBnJaKSvOpJGz8mfZ"
        },
        "href" : "https://api.spotify.com/v1/artists/5M52tdBnJaKSvOpJGz8mfZ",
        "id" : "5M52tdBnJaKSvOpJGz8mfZ",
        "name" : "Black Sabbath",
        "type" : "artist",
        "uri" : "spotify:artist:5M52tdBnJaKSvOpJGz8mfZ"
      } ],
      "available_markets" : [ ],
      "external_urls" : {
        "spotify" : "https://open.spotify.com/album/6r7LZXAVueS5DqdrvXJJK7"
      },
      "href" : "https://api.spotify.com/v1/albums/6r7LZXAVueS5DqdrvXJJK7",
      "id" : "6r7LZXAVueS5DqdrvXJJK7",
      "images" : [ {
        "height" : 640,
        "url" : "https://i.scdn.co/image/7683bcf0385767362266d963876c79b6f0390020",
        "width" : 640
      }, {
        "height" : 300,
        "url" : "https://i.scdn.co/image/7496c43be71babb22e3ca2e4aca7959b8220362a",
        "width" : 300
      }, {
        "height" : 64,
        "url" : "https://i.scdn.co/image/c6a10fcba796de65bddcdd17444be0443ecc4f2f",
        "width" : 64
      } ],
      "name" : "Paranoid (Remastered Edition)",
      "type" : "album",
      "uri" : "spotify:album:6r7LZXAVueS5DqdrvXJJK7"
    },
```

This is one example entry of the playlists json:

```
{
  "href" : "https://api.spotify.com/v1/users/username/playlists?offset=0&limit=50",
  "items" : [ {
    "collaborative" : false,
    "external_urls" : {
      "spotify" : "http://open.spotify.com/user/username/playlist/6AeFboOOynnG11HdX4fJGw"
    },
    "href" : "https://api.spotify.com/v1/users/username/playlists/6AeFboOOynnG11HdX4fJGw",
    "id" : "6AeFboOOynnG11HdX4fJGw",
    "images" : [ ],
    "name" : "TEST",
    "owner" : {
      "external_urls" : {
        "spotify" : "http://open.spotify.com/user/username"
      },
      "href" : "https://api.spotify.com/v1/users/username",
      "id" : "username",
      "type" : "user",
      "uri" : "spotify:user:username"
    },
    "public" : true,
    "snapshot_id" : "zUYrC9QpEFKGiHG3SWUdlssncATrsodX+ppvuOHmpZyfvrnTjocv7P368wsw1+2H",
    "tracks" : {
      "href" : "https://api.spotify.com/v1/users/username/playlists/6AeFboOOynnG11HdX4fJGw/tracks",
      "total" : 0
    },
    "type" : "playlist",
    "uri" : "spotify:user:username:playlist:6AeFboOOynnG11HdX4fJGw"
  },
```

In ncmpcpp I get playlists and the search is also working so the problem is definitely within mopify. I hope to provide enough details to fix this issue. If you need more feel free to ask.

**Comment by mstruebing** [comment]
Ok,it was an error with my spotify playlists.

**Comment by kingosticks** [comment]
Could you be more specific for anyone else that hits this? How did you resolve it?

**Comment by mstruebing** [comment]
The error was that I had a falsy playlist in my spotify account, mopify did a request to a non existing playlist which results in this runtime error. I wrote the spotify support to remove this playlist from my account and now it is working fine. 
I investigated the request and saw in the json result that the playlist is not really existing, but is somehow connected to my account.

**Comment by kingosticks** [comment]
Super, thank you!
