### ISSUE TITLE
Mopify not playing songs

### ISSUE THREAD

**Issue by UnicornDoggo** [dirkgroenen/mopidy-mopify#233]
Hi,
I recently set up Mopidy-Mopify on a Raspberry Pi. After everything was done loading, I opened Mopify on a browser on a laptop. I connecting Spotify and the Sync service, and my songs synced to the website. However after trying to play a song, things started going wrong. The bar at the bottom, that controls the volume, pause and play, said "Connecting" or something (it later stopped saying that instead said "connected"), and the ticker thing that says how far you are into a song started to count. There was no song playing. I made sure my volume was up. I reloaded the page. I started mopidy on the pi again. It's still not working. the ticker thing will count and count for hours if you let it, and no song will play. I also can't pause, play, moderate volume, turn on shuffle, or do anything else using the bar at the bottom. I am disappointed because I was really excited to set this up. I've Googled my issue but haven't found anyone with the same problem I am having. Help would be much appreciated.

**Comment by Wellukene** [comment]
I have the same problem. The two times I tried to install the software again, and that did not help either. She waits for the answer.

**Comment by Goontown** [comment]
I have the same problem as well, i thought that it was a pure audio problem but sense we are all in the same boat here it might be something else. 

I have tried to use diffrent programs for audio output but the original is the only one that makes sound come out when using :
gst-launch-1.0 audiotestsrc ! audioresample ! autoaudiosink
