### ISSUE TITLE
Update to mopidy 3

### ISSUE THREAD

**Issue by MarcinWieczorek** [dirkgroenen/mopidy-mopify#240]
Hello
Is this project still alive?
Is it going to be updated to python3/mopidy3?
I'm getting `ModuleNotFoundError: No module named 'mem'` error.

Thanks.

**Comment by binoix** [comment]
+1

**Comment by dirkgroenen** [comment]
Fixed by 1.7.0 which was released last week.

**Comment by kingosticks** [comment]
Does this project now support both Mopidy (Python) 2 and 3, or just 3? The version requirements still specify >0.19 and the readme install instructions are for Python 2 (in practice). If it's just Mopidy 3 that's supported, that's fine but could you update those bits of project scaffolding.

**Comment by dirkgroenen** [comment]
Just cleaned it up a little @kingosticks.

I'm no Mopidy user myself anymore, so please let me know if there's anything else I can do.
