### ISSUE TITLE
Search does not work

### ISSUE THREAD

**Issue by DerT94** [dirkgroenen/mopidy-mopify#246]
Hi,

Unfortunately, the search does not work for me.
When I search for a song or a band I get no result.

![image](https://user-images.githubusercontent.com/58786605/88073297-51f7df80-cb76-11ea-9699-c61bd7435e27.png)

**Comment by tombeareatscake** [comment]
I can confirm this is also happening for me on various browsers.
Chromium: Version 84.0.4147.89 (Official Build) Arch Linux (64-bit)
Chrome: Version 84.0.4147.89 (Official Build) (64-bit)
Firefox : 78.0.2 (64-bit) Arch Linux (64-bit)

Just wanted to say this is the best mopidy interface... if this search worked as well it would be amazing.
