### ISSUE TITLE
no connection

### ISSUE THREAD

**Issue by DerT94** [dirkgroenen/mopidy-mopify#247]
Hi,

mopify get no connection to soptify service.
![image](https://user-images.githubusercontent.com/58786605/88903937-b4c33800-d254-11ea-9766-d0ff4d9cc5c0.png)

If i click "Reconnect with Spotify" a window opens briefly in which successfull login is written.

**Comment by qbradford** [comment]
Try opening in Firefox. I receive this in Chrome. A check in the console revealed a same site cookies error: `Failed to load resource: the server responded with a status of 401 ()
mopidy-mopify-1.7.3.js:47384 TypeError: Cannot read property 'images' of undefined
    at mopidy-mopify-1.7.3.js:46783
    at g (mopidy-mopify-1.7.3.js:19023)
    at mopidy-mopify-1.7.3.js:19039
    at o.$eval (mopidy-mopify-1.7.3.js:20297)
    at o.$digest (mopidy-mopify-1.7.3.js:20110)
    at o.$apply (mopidy-mopify-1.7.3.js:20405)
    at i (mopidy-mopify-1.7.3.js:14556)
    at u (mopidy-mopify-1.7.3.js:14762)
    at XMLHttpRequest.x.onload (mopidy-mopify-1.7.3.js:14695)
(anonymous) @ mopidy-mopify-1.7.3.js:47384
mopidy-mopify-1.7.3.js:48363 Websocket: connection ready
:6680/mopify/#/discover/featured:1 A cookie associated with a cross-site resource at http://bitlabs.nl/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
6:6680/mopify/#/discover/featured:1 Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at mopidy-mopify-1.7.3.js:49042
61VM113:1 Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at mopidy-mopify-1.7.3.js:49042`

**Comment by jeffanberg** [comment]
If you wish to continue using chrome, you can also edit the cookie directly by going to the Inspect tool -> Application -> Cookies and changing the SameSite value to "None" and enabling the "Secure" value.

**Comment by DerT94** [comment]
Sorry for the late response.

It works with Firefox

**Comment by ejancorp** [comment]
Experience this one also, but firefox is fine, what I did is use firefox, connect spotify, enable sync, set force sync on, enable spotify credentials, then push. Then go to my edge and chrome browser and enable sync. Then connect spotify, if credentials didnt get synced click get to retrieve credentials manually.
