### ISSUE TITLE
Can't Access Mopify

### ISSUE THREAD

**Issue by skinnx86** [dirkgroenen/mopidy-mopify#248]
Hello, 

I have run through all the commands to get mopidy running on my Pi Zero and followed the instructions to get mopify installed but it does not show as an extension in the mopidy web interface and `192.168.0.32/6680/mopify` returns a 404 error.

**Comment by dirkgroenen** [comment]
It doesn't sound like a Mopify specific issue, so you might have some look pinging the community of Mopidy. 
You might want to verify your installation though, make sure you're using the same version of Python/Pip, the same user/environment and things like that. Check your logs and see if there's any error which might help you to proceed.

**Comment by skinnx86** [comment]
Thank you, I'll try those.
