### ISSUE TITLE
Stations dont seem to work

### ISSUE THREAD

**Issue by vrs01** [dirkgroenen/mopidy-mopify#25]
Hi!

I can create stations but when I click on the symbol 'wifi' nothing happens. Can I start the stations differently?

I have Mopify 1.1.2 installed on Pimusicbox 0.5.2

**Comment by dirkgroenen** [comment]
Where are you clicking on the symbol? There are different ways to create a new station:
 - Stations page
 - Right click context menu on tracks, albums, playlist etc.
 - Right top corner on playlist, album and tracklist page

What happens when you click on the icon? Does it show a blue loading bar in the screen's top?

**Comment by vrs01** [comment]
Yes, I get the blue loading bar. The bar also finishes til the right edge of the screen. The current playing track is stopped but still shown in the bottom bar. The current tracklist is deleted. It's the same with all three of the ways you mentioned.

**Comment by dirkgroenen** [comment]
Hmm that's weird. Do you get any messages in your browser's console, are tracks added to your tracklist and does your Mopidy still respond after starting the station?

**Comment by vrs01** [comment]
Ok I need the taste profile activated for the stations. I didn't realize that. The 'browse' section warns you when the taste profile is not connected. Maybe that would be nice for the 'stations' as well? 

Another thing: Can I delete individual stations (without deleting the browser cache)?

The rest is really working nicely! Thanks a lot!

**Comment by dirkgroenen** [comment]
Hmm that has to be a bug, cause stations are supposed to work even without taste profiles enabled. I'll check it out.

**Comment by vrs01** [comment]
I think the stations are still not working. There is now tracks added to the queue. Mopify and mopidy are still responding after clicking on a station.
I get this erreor in the browser console (Firefox and chrome)
```
"Server returned error:" Object { message: "Application error", code: 0, data: Object } mopidy-mopify-1.1.4.js:30
```

**Comment by dirkgroenen** [comment]
Hmm that looks like a Mopidy error. Which Mopidy and Mopidy-Spotify version are you using?

**Comment by vrs01** [comment]
mopidy 0.19.5
mopidy-spotify 1.2.0

**Comment by vrs01** [comment]
Ok in the new pimusicbox 0.5.3 the stations work fine.
