### ISSUE TITLE
Spotify Login is successful, but service stays "Disconnected"

### ISSUE THREAD

**Issue by rdrr** [dirkgroenen/mopidy-mopify#254]
Tried on Edge and Firefox. The dev tools in firefox give this warning from the console: 

`Uncaught SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
<anonymous> mopidy-mopify-1.7.3.js:49042`

(And basically the same message in the Edge Dev Tools)

A popup happens every 60 seconds or so and briefly says "Login Successful" before closing immediately.  Iris works great with Spotify.  It seems like mopidy is not parsing the respone from Spotify correctly.  Running Mopidy 3.2.0, mopify 1.7.3, python 3.7.3 on a ubuntu server.  

Thanks for any help.  Hope this helps out too.

**Comment by scetu** [comment]
Hey, have you found solution or is this project dead? Just getting same error.
