### ISSUE TITLE
Disconnect Spotify Account

### ISSUE THREAD

**Issue by janw86** [dirkgroenen/mopidy-mopify#27]
I have encountered the following problem: 

I tried to connect with spotify but for some reason I cannot establish the connection with the server. So I tried to delete my input and reestablish the connection, but I cannot find the option. 

Even after reinstalling modipy-mopify all the preferences are still there. How can I delete the link to my spotify account?

Thank you for your great work

**Comment by dirkgroenen** [comment]
The tokens are saved in your local storage (editable via the Developer Tools in Chrome). At the moment there is no way of removing these saved tokens. 

But, when connecting the Spotify service it should try to log-in to Spotify. If that doesn't work it will try to prompt the Spotify login window so you can enter your credentials. When you're already logged in to Spotify this prompt will immediately close.

I will create a new Issue with the idea to remove the account credentials form within the service's settings, but for now you have to remove the tokens manually from your local storage. You can do that by following these steps:

- Open Chrome and open the Developer tools (F12)
- Go to ```Resources```
- Expand ```Local Storage``` on the left side and click on the domain you're using to access Mopify.
- Click on the ```mopify.spotifytokens``` row which will highlight it
- Click on the 'X' in the bottom of the screen

Your tokens are now removed and if you re-enable the service it will prompt the login window.

**Comment by janw86** [comment]
Thank you for your answer. I am using Safari and I was indeed able to reset the sign in information by clearing website data. In firefox the connection to spotify is possible, in Safari I cannot connect to Spotify with the same login data. 

Any ideas or is Safari not supported?

**Comment by dirkgroenen** [comment]
I haven't tested Mopify in Safari yet. I will test this for you when I'm at the office tomorrow.
