### ISSUE TITLE
Add Spotify Collection

### ISSUE THREAD

**Issue by daphee** [dirkgroenen/mopidy-mopify#32]
It would be nice to have "My Music" integrated like in the official Spotify clients.
This wasn't possible with libspotify but is with the newer Web API. Mopify is already connecting to this API so why don't integrate your Spotify Collection?

**Comment by totokaka** [comment]
:+1: 

This is a must have for me. Organizing my music by artists and albums is so much better than shittons of playlists, and the my music collection is so much faster to navigate than searching all of spotify.

**Comment by dirkgroenen** [comment]
I've never used this Spotify feature, but I assume you're referring to the [/me/tracks](https://developer.spotify.com/web-api/get-users-saved-tracks/) endpoint? I don't see any other collection look a like endpoints in Spotify's web api.

**Comment by daphee** [comment]
Yes.

**Comment by dirkgroenen** [comment]
Allright, any idea on how you would like to see this feature? As I said I have never used this before, but I assume that you use it in a same way you use playlists?

**Comment by daphee** [comment]
In the Browser you can view your Collection on http://play.spotify.com at "/collection/[artists,albums,songs]". I mostly use "/collection/albums". This way I can browse my music like I would using iTunes or a similar software. Scroll through albums -> Either play whole album OR view tracks and play specific one.

**Comment by tindzk** [comment]
As @daphee mentioned, there are three ways to view the collection. I guess, you don't even need to create any new views and can reuse the existing playlist and album lists.

However, the desktop application provides a 'plus' button to add songs and albums to the collection. These songs are automatically synchronised with the smartphone for example. Adding/removing such songs would be greatly appreciated because this is the only feature that prevents me from migrating completely to Mopify.

**Comment by dirkgroenen** [comment]
The only available endpoint at the moment is the ```/me/track``` endpoint, which saves a given track to the user's Your Music library/collection.

I can implement this feature, but the other types (albums and artists) aren't possible at the moment.

**Comment by totokaka** [comment]
Albums and artists are actually populated from the tracks. If you save one
track from an album the artist and that albums shows up in the artists and
albums view respectively, but only with that one song.

Thanks for looking into this!
15. feb. 2015 13:00 skrev "Dirk Groenen" <notifications@github.com>:

**Comment by dirkgroenen** [comment]
At the moment I've integrated the songs and albums. It looks like artists is filled with artists the user is following, so not the artists that appear in one of the saved tracks.
Problem is that there isn't an endpoint for retrieving the user's artists, so we have to wait with that feature. 

I'm testing the new songs and albums features at the moment.

**Comment by totokaka** [comment]
According to my spotify it would be both. I have some artists in my artists
view that I don't follow, but that I have saved songs from. And if I follow
an artist without saving any songs, that artist shows up too.
15. feb. 2015 15:26 skrev "Dirk Groenen" <notifications@github.com>:

**Comment by dirkgroenen** [comment]
Allright, in that case I'll add the artists that I can subtract from the songs. I've sent Spotify a tweet asking if they have an 'User's Following Artists' endpoint, since its not in the endpoint reference.

**Comment by dirkgroenen** [comment]
This has been implemented in release 1.2.0 which I've just uploaded.
