### ISSUE TITLE
Add genre playlists

### ISSUE THREAD

**Issue by tindzk** [dirkgroenen/mopidy-mopify#33]
Currently, only 'featured playlists' are supported. I usually listen to Spotify's precompiled 'genre playlists'. Would it be possible to add support for these as well?

**Comment by dirkgroenen** [comment]
The Spotify web api has no genre endpoint, but [Echonest](http://developer.echonest.com/docs/v4/genre.html) does. I'll check the possibilities.

**Comment by dirkgroenen** [comment]
Removed milestone since neither Spotify or Echonest provides a way to retrieve a list of popular of 'general' genres.

**Comment by dirkgroenen** [comment]
Update: Noticed that Spotify has added a [categories endpoint](https://developer.spotify.com/web-api/get-list-categories/) to their API which should make it possible to add genres.
