### ISSUE TITLE
Add tooltips

### ISSUE THREAD

**Issue by tindzk** [dirkgroenen/mopidy-mopify#36]
I had to look at the DOM in order to understand that the first button refers to popular tracks and the third button starts the artist's radio when hovering over the cover image in ``/discover/browse``. Tooltips will help new users to grasp the UI faster.

**Comment by dirkgroenen** [comment]
This was already added as an issue in #15. I'll close that one and move on in this thread.

**Comment by dirkgroenen** [comment]
Tooltips have been added to the Album's, Artist's and Playlist's icons.
