### ISSUE TITLE
Update song details faster

### ISSUE THREAD

**Issue by tindzk** [dirkgroenen/mopidy-mopify#37]
When playing a new song, the song details in the bottom toolbar get updated only after a delay of several seconds. However, this information is already known from the playlist in many cases. If the information cannot be fetched from the cache, it may make sense to indicate that the details are currently being loaded. As of now, the previous song remains to be shown which led to some confusion on my behalf.

**Comment by dirkgroenen** [comment]
At the moment the information changes on a [trackPlaybackStarted](https://github.com/dirkgroenen/mopidy-mopify/blob/master/src/app/player/player.controller.js#L44-L55) event, but I've also noticed this doesn't always work properly. 

When the new track is started and the event is fired it should show the information right away since the track is parsed via the event. 

It could be solution to add an interval that checks the current playing song and update it when needed.

**Comment by kingosticks** [comment]
If this doesn't work properly in Mopidy we'd love a reproducible bug report
and to fix it.  Polling these things is very unfriendly for low-performance
devices.

**Comment by dirkgroenen** [comment]
That's the reason why I didn't choose for that solution when developing. I only/mostly experience this when using Mopidy on a Raspberry and when connected for a longer time. Any idea why it could happen, otherwise I should check the [mopidy-mopify service](https://github.com/dirkgroenen/mopidy-mopify/blob/master/src/app/services/mopidy.service.js).

**Comment by dirkgroenen** [comment]
The client is already pulling [every second](https://github.com/dirkgroenen/mopidy-mopify/blob/master/src/app/player/seekbar/seekbar.controller.js#L53-L55) to get the current time. Do you know about a good alternative for this @kingosticks?

**Comment by kingosticks** [comment]
No I don't I'm afraid, but to be honest I've not looked into it. That is the only solution so far to get the time but every second is quite a lot. I think the only issue on it is https://github.com/woutervanwijk/Mopidy-MusicBox-Webclient/issues/40

**Comment by dirkgroenen** [comment]
I found out that the event listener for refreshing the track was placed in an other event listener. I've move it out of this listener in the hope that it will work better now.

The seekbar/times have been changed to. The script will now pull the current timeposition every 10 seconds. In the time between that it will just add the seconds using an interval. Hopefully this will give Mopidy some more rest.

**Comment by tindzk** [comment]
Shouldn't this be easy to fix if we were just using WebSockets instead? Then, Mopidy could notify us as soon as it has the information.

**Comment by dirkgroenen** [comment]
Getting the latest information is done by a websocket listener. Mopidy should fire the ```trackPlaybackStarted``` event ([https://github.com/dirkgroenen/mopidy-mopify/blob/master/src/app/player/player.controller.js#L45-L56](player.controller.js)) which passes the new track as data. This data is used to refresh the player's information.

I've tested it on my computer at home, as well as on the (usually slower) Raspberry at the office and both times I get the new track information immediately.

**Comment by tindzk** [comment]
Ah, I thought Mopidy only supported polling. I just upgraded Mopify including its dependencies, but the bug still remains. On my Raspberry Pi I've seen delays of up to 18 seconds. I don't know whether we can do anything about this, but it would certainly improve the usability if the page title and the meta information could just be cleared while we are waiting for the event to arrive. You may also want to indicate that we are waiting with a spinning icon in the song bar (see http://fortawesome.github.io/Font-Awesome/examples/).

**Comment by dirkgroenen** [comment]
Hmm that are some serious delays. I've never seen such a delay before, but I have seen Mopify losing it's 'event listener' which results in a non-updating player. Are you sure that that isn't the problem? 

I'm wondering how the seekbar behaves when the player isn't updating it's meta data. Does it update the time properly? 

Adding  a spinner is a nice idea, but it would need the event to fire up. It sounds like the event doesn't fire up at all so showing the spinner wouldn't be possible. As I sad, the moment the event fires it gives the new track data.

Can you check the websocket's frames in your Chrome Develop tools? (Developer tools > Network > ws > Frames). It should show something like this: [Develop Tool preview](http://i.imgur.com/HjM5Hg0.png). In this example you see the ```playback_state_changed``` event in the 8th row.

**Comment by tindzk** [comment]
I checked in the Chrome Developer Tools and I receive ``playback_state_changed`` with a delay of several seconds and then a few seconds later I get the meta information. The seekbar also doesn't behave entirely as it should. After manually changing the song in the playlist, it changes to 00:00 and progresses every second. After a short time, it starts with 00:00 again (probably because Mopify received the state change).

**Comment by brantje** [comment]
Is it possible to fetch the next song information about 20 seconds before the current song ends? That way we can have the info ready when it's needed.

**Comment by dirkgroenen** [comment]
The seekbar indeed needs some extra fine tuning, but the problem you have with the refreshing meta data is a real mystery for me.

Preloading the next track's meta data won't work since I don't know what Mopidy is going to play next. Especially when shuffle is enabled it isn't possible to receive the next track.

@tindzk do you have this problem too with other Web clients?

**Comment by tindzk** [comment]
I think the seekbar is actually behaving correctly. In my case, I'm receiving ``playback_state_changed`` after a few seconds and this is what causes the delay in the UI. As long as we cannot get any information about the next song, there is probably no workaround.

**Comment by dirkgroenen** [comment]
Which brings me at where I'm wondering how your Mopidy interface is running? Down at the office I've installed Mopidy in combination with nginx (which runs Mopify). Besides the overall Raspberry-Mopidy slowness I don't have any problems like this.

**Comment by tindzk** [comment]
I installed Mopidy with the Spotify plugin exactly as explained [here](https://docs.mopidy.com/en/latest/installation/debian/) and [here](https://docs.mopidy.com/en/latest/ext/http/). There is no intermediate server like nginx. The Raspberry Pi is connected via Wi-Fi.

**Comment by dirkgroenen** [comment]
Hmm ok, weird. Do you encounter the same problem when using an other web client?

**Comment by tindzk** [comment]
Yes.

**Comment by dirkgroenen** [comment]
In that case you might want to open an issue in the official Mopidy repo. It sounds more like a problem with your Mopidy setup, or mopidy, than with Mopify.

**Comment by tindzk** [comment]
Ok, I guess we can close this issue then for now.
