### ISSUE TITLE
Right click options hidden behind seek bar

### ISSUE THREAD

**Issue by bigmittens** [dirkgroenen/mopidy-mopify#39]
![2015-01-27-231856_1920x1080_scrot](https://cloud.githubusercontent.com/assets/2244606/5933917/29de0094-a67c-11e4-9620-94b9f8a71184.png)

**Comment by dirkgroenen** [comment]
Thanks, will fix it.

**Comment by dirkgroenen** [comment]
Has been fixed in 1.1.5
