### ISSUE TITLE
Display more than 10 artists/albums/tracks

### ISSUE THREAD

**Issue by siejeje** [dirkgroenen/mopidy-mopify#40]
Search function currently returns only 10 artist, albums, tracks and playlists. Would it be possible to add some "more+" button to show more results?

**Comment by vdbee** [comment]
I agree, that would be nice to have

**Comment by dirkgroenen** [comment]
Will take this with me when developing version 1.1.5.

**Comment by dirkgroenen** [comment]
I've added buttons on the search page which will show up to 50 results instead of the default 10.
