### ISSUE TITLE
local files and radio as well

### ISSUE THREAD

**Issue by vdbee** [dirkgroenen/mopidy-mopify#41]
Besides Spotify, I also use radio and local music files quite often. Did you plan to add that kind of functionality?

**Comment by bigmittens** [comment]
+1 for local music.

**Comment by dirkgroenen** [comment]
As mentioned in the README I might consider that based on the client's popularity. My goal at the moment is to provide a great (bug-free) client for Mopify in combination with Spotify, but I definitely don't rule out the possibility of adding other music sources.

**Comment by dirkgroenen** [comment]
Little update on this:

I first want to bring the current extension to a 'perfect' extension. When most of the current bugs and missing features are solved/implemented I will put some time in adding other services. 

I'll add this to milestone 2.0.0 which will hopefully see it's first development life within the next few weeks.

**Comment by adiktofsugar** [comment]
Hey, how do you see / develop with the 2.0 mopify? I really want soundcloud too, and am down with fixing things. (i apologize if this is the wrong place to post this)

**Comment by dirkgroenen** [comment]
At the moment there is no branch for mopify 2.0. I'm currently still thinking about a way on how to blend more services like soundcloud with the current interface.

**Comment by dirkgroenen** [comment]
I've opened a new issue which will be the new discussion point for Mopify 2.0 and it's extra services. #113
