### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by simonsmiley** [dirkgroenen/mopidy-mopify#42]
I would really like a favicon, so I can "pin" the tab and see what it is. Since I don't think you have any logo, how about something like [this](http://www.favicon.cc/?action=icon&file_id=771711)? It's creative commons _without_ attributions

**Comment by dirkgroenen** [comment]
Good one, will add one in the next release.

**Comment by dirkgroenen** [comment]
Favicon has been added for now.

**Comment by simonsmiley** [comment]
wow, that was fast :D thanks!
