### ISSUE TITLE
Copy link

### ISSUE THREAD

**Issue by vdbee** [dirkgroenen/mopidy-mopify#45]
I like to share links of single tracks. Would it be possible to have an option in the "right click menu" to copy the spotify-link of that track?

**Comment by dirkgroenen** [comment]
Which link would you like to copy, the Spotify URI or HTTP link?

**Comment by vdbee** [comment]
I prefer the HTTP link

**Comment by dirkgroenen** [comment]
Ok, I'll consider adding it. ;)

**Comment by Joeasaurus** [comment]
+1 for this ability, though personally I find the Spotify URI much more useful. 

The Spotify URIs can be used to open the official client directly, if your machine is set up correctly (same as magnet URIs + a torrent application). 

The HTTP links will take you to Spotify's web client, which is not that nice. If it was desirable to direct people there and use it, then I wouldn't use Mopify!
