### ISSUE TITLE
Duplicated albums

### ISSUE THREAD

**Issue by Bahaika** [dirkgroenen/mopidy-mopify#47]
Since version 1.2.0 which added Album supports, I noticed that some albums are duplicated in the view.
![screen shot 2015-02-18 at 18 18 07](https://cloud.githubusercontent.com/assets/3199214/6252445/ab874694-b79a-11e4-9dc6-00b9bfc07686.png)

**Comment by dirkgroenen** [comment]
Mopify uses the [album's ID](https://github.com/dirkgroenen/mopidy-mopify/blob/master/src/app/music/library/albums/albums.controller.js#L65-L67) of each song to create the album view. Is it possible that some of your 'double albums' are actually two different albums? 

Should be easy to check by opening the tracklist of both albums and comparing the Spotify URI in the URL.

**Comment by Bahaika** [comment]
I checked the album's ID : 
First "Nero - Walcome Reality" : `spotify:album:02Zb13fM8k04tRwTfMUhe9`
Second "Nero - Walcome Reality" `spotify:album:02Zb13fM8k04tRwTfMUhe9`
It seems to be the same album showed twice. Maybe before adding an album to the view you can check if the same ID is already shown ?

**Comment by dirkgroenen** [comment]
That's weird since the ```_.unique()``` function should remove the doubles in the list. Can you find something strange with the double albums when checking the 'Songs' list?

**Comment by Bahaika** [comment]
No, nothing. The track lists are the same. There's nothing wrong with the tracks list.

**Comment by dirkgroenen** [comment]
I'll add some more tracks to my own library which will hopefully produces the bug. Otherwise I don't really know what causes the double albums, since ```_.unique()``` should have removed them.

**Comment by Bahaika** [comment]
Ah, great you figured it out ! Will it be hard to fix ?

**Comment by dirkgroenen** [comment]
No it should be quite easy to fix. Might fix and release a new version today.

**Comment by dirkgroenen** [comment]
Fixed in 1.2.1.

**Comment by Bahaika** [comment]
It's working well, thank you.
