### ISSUE TITLE
Play next option

### ISSUE THREAD

**Issue by dirkgroenen** [dirkgroenen/mopidy-mopify#49]
Add a Play Next option in the context menu which adds a track, album or playlist in the queue at the second position.

**Comment by vdbee** [comment]
Could it be that this option got removed during one of the last updates? I don't have it available anymore.

**Comment by dirkgroenen** [comment]
Hmm that's weird. I can't find any references to the play next button in de code anymore. Looks like something went wrong when I resumed developing on an other PC today.

I'll look into it tomorrow.

**Comment by dirkgroenen** [comment]
Just remembered that the function didn't worked as supposed, so I probably removed it when I continued developing although I must say that I can't remember that...

**Comment by dirkgroenen** [comment]
In version 1.5.0 Mopify will have it's own queue manager which will make Mopidy's queue align with Spotify's.
