### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by vrs01** [dirkgroenen/mopidy-mopify#50]
Hi!

Could we have some keyboard shortcut like 'Space' for playing/pausing?

**Comment by dirkgroenen** [comment]
Definitely! Already on my to do list ;)

**Comment by dirkgroenen** [comment]
Mopify now supports keyboard shortcuts (Release: 1.2.3)

**Comment by kingosticks** [comment]
I'll say it here since I can't comment on  a release, you are doing a
fantastic job with this. Thanks very much.

**Comment by dirkgroenen** [comment]
Thanks, I appreciate that which motivates me to further develop this project!
