### ISSUE TITLE
Sorting of artists, albums and songs in collection

### ISSUE THREAD

**Issue by tlaundal** [dirkgroenen/mopidy-mopify#52]
First of all, thank you for all your great work on mopify! I'm on my way to migrate from the outdated spotify linux client.

Currently, artists and albums in the user's collection seems to be sorted in the order they where 'saved' to the user's collection. Spotify sort albums and artists, in the artists and albums view, respectively, like this:
- First by artists alphabetically
- Then by album name alphabetically

Songs are almost sorted correctly as they are now, but not quite. It seems spotify sorts the songs by this pattern:
- First by the date the element was 'saved'. Element can be album or song (I think)
- Then by track number in the album it belongs to

The song order doesn't matter at all for me, but artists and albums are very hard to navigate the way it is now.

**Comment by dirkgroenen** [comment]
So you would suggest ordering artists and albums alphabetically? If I look at Spotify's official web client it provides four ways of sorting. Three of those could be integrated into Mopify.

![http://i.imgur.com/QdLCres.png](http://i.imgur.com/QdLCres.png)

**Comment by totokaka** [comment]
Sorry, I completely forgot about the option on what to sort after in the official clients.

I have artits sorted after "name", albums sorted by "artist" and songs sorted by "recently added". These are the settings that produce the results in the opening posts, and are the ones I want the most.

**Comment by dirkgroenen** [comment]
Songs are already sorted by the moment of adding (at least when I look at my songlist). For the album and artist page I will add a feature to enable sorting on "Artist", "Title" or "Moment of adding".

**Comment by totokaka** [comment]
The problem with the "Moment of adding" sorting which is currently implemented appears when you add a whole album. In the official clients, the songs, when sorted by "Moment of adding" will be sorted by the album order if they where added collectively as an album.

**Comment by dirkgroenen** [comment]
Spotify returns a ```track_number``` with each track so it should be possible to implement this extra sorting. I'll look into it.

**Comment by totokaka** [comment]
Here is how I'd like the albums view to maybe look:
![](http://i.imgur.com/JTfrzCF.png)
That's just a quick mockup I made by editing the HTML of the existing design in my browser. With this view it makes most sense to sort the albums based on the artist's name. Alternatively the headline could be just the first letter, and all artists starting with that letter would be placed under it.

**Comment by dirkgroenen** [comment]
Definitely a nice idea. At the moment I've added the album's artists under each album so you can see who the album belongs to. 

Adding the album cover images as mosaic is an idea I already have, but I want to focus on the 'core' problems first.

**Comment by StanSvec** [comment]
Hi Dirk, Can you please update on this sorting feature? Is this still in plan?

**Comment by dirkgroenen** [comment]
Right now I'm quite busy with work and other stuff so I atm I can't start something big.
