### ISSUE TITLE
Popup when loading the web interface

### ISSUE THREAD

**Issue by totokaka** [dirkgroenen/mopidy-mopify#53]
When I go to the web interface, or when I reload it, I get a big, empty, pop up that closes itself right after it opens.It would be nice to get rid of this pop-up.

**Comment by dirkgroenen** [comment]
This popup is the Spotify Service login procedure. It won't show (or at least it shouldn't) when you disable the [Spotify service](https://github.com/dirkgroenen/mopidy-mopify/wiki/Services#spotify).

**Comment by dirkgroenen** [comment]
I've fine-tuned the Spotify login procedure so it makes more use of the refresh_token. This should result in a less showing popup.

**Comment by vdbee** [comment]
Thanks again for this quick update, it even more improved the user friendliness. Thanks!


--- Oorspronkelijk bericht ---

Van: "Dirk Groenen" <notifications@github.com>
Verzonden: 23 februari 2015 20:57
Aan: "dirkgroenen/mopidy-mopify" <mopidy-mopify@noreply.github.com>
Onderwerp: Re: [mopidy-mopify] Popup when loading the web interface (#53)

I've fine-tuned the Spotify login procedure so it makes more use of the refresh_token. This should result in a less showing popup.

---
