### ISSUE TITLE
Artists and albums in collection links to 'wrong' pages

### ISSUE THREAD

**Issue by tlaundal** [dirkgroenen/mopidy-mopify#55]
My wish is to have mopify behave as much like spotify as possible, especially in regards to the 'collection' feature from spotify. This issue is therefore mainly how I'd like it to be.

Currently when I click an artist in the artists view, I am redirected to the artist's page, and when I click and album in the albums view, I am redirected to the album's page.

In spotify, clicking an artist gives you a view with the albums you have saved from that artist, and clicking an album (either from the albums view or from the view I was talking about), gives you a view with the saved tracks on that album.

**Comment by dirkgroenen** [comment]
Sounds good for me, I'll see what I can do.
