### ISSUE TITLE
Unresponsive script

### ISSUE THREAD

**Issue by totokaka** [dirkgroenen/mopidy-mopify#56]
I had this error a couple of times earlier today. I haven't seen it for the past hour.
![abalqsf](https://cloud.githubusercontent.com/assets/817001/6320015/ba5bc3b6-bad3-11e4-8da3-cc782835e87b.png)
From what I remember the line number would be `9` the first time the error popped up, and then change for each time I clicked "Stop script" or "Continue" (The whole browser was lagging, the error would keep reappearing until I killed the browser).

I am running Firefox 35.0.1 on linux. It made the whole browser hang, so I had to kill the firefox process.

**Comment by dirkgroenen** [comment]
Have seen this window before when using Firefox and opening a big tracklist (for example your Song collection or a huge playlist). The huge playlists are chucked up in multiple parts which get loaded when you scroll down. The song collection doesn't do this (I'm now remembering that I forgot to implement this) . 

Can you confirm that this is happening when opening your Song collection of any other page with many DOM element?

**Comment by totokaka** [comment]
Yes, I can confirm that. The browser starts loading and hangs after just a second when I open the song collection.

**Comment by dirkgroenen** [comment]
Ok, will be fixed in the next release.

**Comment by 5paceManSpiff** [comment]
In my case I get a process out of memmory error when loading my song list.

**Comment by dirkgroenen** [comment]
Found the problem that causes these huge memory drains and fixed it for next release ( #29 / 7889a48 ).

**Comment by dirkgroenen** [comment]
Fixed in 1.3.1 which I've just released. I've tested it with a playlist containing 2000 tracks and everything went well.
