### ISSUE TITLE
Shuffle icon not active when using the "SHUFFLE" buttons

### ISSUE THREAD

**Issue by totokaka** [dirkgroenen/mopidy-mopify#57]
When I go to a playlist and hit the "SHUFFLE PLAYLIST" button, or to an album and press the "SHUFFLE ALBUM" button, the shuffle icon in the control section stays as it was before i clicked the button.

This is probably related to a bigger design problem of how the shuffeling is implemented. It seems like the "SHUFFLE" buttons will put the album or playlist in the play queue in shuffeled order. On the other hand, the shuffle icon/button in the control section will play songs randomly from the play queue. 
The official client will shuffle the play queue when the shuffle icon/button is active, and put it back in order when it's deactivated.

I think these two ways to shuffle should be implemented so they cooperate and give a consistent user experience.

**Comment by dirkgroenen** [comment]
Since Mopidy has the official control over the way how the shuffle mode works I would suggest we change the way how Mopify's Shuffle button works. 

Which will mean: putting all tracks in the queue in normal order, starting a random track and enable the shuffle mode.

**Comment by totokaka** [comment]
Sounds just fine.

**Comment by dirkgroenen** [comment]
Fixed in 1.3.1 which I've just released.
