### ISSUE TITLE
Currently playing song should be clickable

### ISSUE THREAD

**Issue by totokaka** [dirkgroenen/mopidy-mopify#59]
When I'm listening to a song I would expect to be taken to the album the song is on when I click the song title or artist name in the currently playing section at the bottom of the screen.

This is by no means important, but it would have been a nice little feature.

**Comment by dirkgroenen** [comment]
Marking as a fine UX idea. Thanks.

**Comment by dirkgroenen** [comment]
I've just released 1.3.1 which contains the clickable track.
