### ISSUE TITLE
Startup error with new version

### ISSUE THREAD

**Issue by bigmittens** [dirkgroenen/mopidy-mopify#60]
```
** Message: pygobject_register_sinkfunc is deprecated (GstObject)
Traceback (most recent call last):
  File "/usr/bin/mopidy", line 9, in <module>
    load_entry_point('Mopidy==0.19.5', 'console_scripts', 'mopidy')()
  File "/usr/lib/python2.7/site-packages/mopidy/__main__.py", line 54, in main
    installed_extensions = ext.load_extensions()
  File "/usr/lib/python2.7/site-packages/mopidy/ext.py", line 155, in load_extensions
    extension_class = entry_point.load(require=False)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2312, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2318, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/mopidy_mopify/__init__.py", line 8, in <module>
    from sync import mopify_sync_factory
  File "/usr/lib/python2.7/site-packages/mopidy_mopify/sync.py", line 9, in <module>
    from configobj import ConfigObj, ConfigObjError
ImportError: No module named configobj
```

**Comment by dirkgroenen** [comment]
Version 1.3.1?

Try:
```sudo pip install --upgrade --force-reinstall mopidy-mopify```

**Comment by bigmittens** [comment]
It's version 1.3.1, right after I upgraded. I'll try a reinstall when I get home in a couple of hours.

**Comment by bigmittens** [comment]
reinstall fixed it. feel free to close.

**Comment by dirkgroenen** [comment]
Good to hear, although I'm quite curious if more people experience this problem. I have three computers running Mopify and one if them also gave me this error after updating. Somebody with more experience in Python that knows where this is coming from?

**Comment by kingosticks** [comment]
I'm not claiming to have much python experience but I'd guess this is
related to how entry points work and you probably want to defer your import
similar to how it's done at
https://github.com/tkem/mopidy-mobile/blob/master/mopidy_mobile/__init__.py

**Comment by dirkgroenen** [comment]
But would it make sense that after a re-install the program does work?

**Comment by kingosticks** [comment]
No, not really. 

I didn't realise ConfigObj wasn't a built in, so it's presumably not picking up the new dependency unless you do a force. I just did a regular `sudo pip install --upgrade` and it worked just fine, but I didn't previously have a version that used configobj. So my next guess that changing the capitalisation is not recognised as a different dependency by pip.

**Comment by dirkgroenen** [comment]
It has been added since version 1.3.0, which lived for only 10 minutes. 1.3.1 Indeed changed the ```configobj``` to ```ConfigObj```. @bigmittens: Can you confirm that you had 1.3.0 installed first?
