### ISSUE TITLE
Memory leak with queue open

### ISSUE THREAD

**Issue by sliepie** [dirkgroenen/mopidy-mopify#61]
Since version 1.2.0 I'm experiencing issues with memory usage, in both chrome and firefox. Currently I'm running version 1.3.1 

With the queue open in firefox, after an hour it's using hundreds of megs of memory:
![image](https://cloud.githubusercontent.com/assets/2635154/6370524/dafd4098-bcf1-11e4-9290-0ca40fc05115.png)

**Comment by dirkgroenen** [comment]
Oh wow, that's not supposed to happen of course. Does it only increase when you have the current queue page open?

**Comment by dirkgroenen** [comment]
I've had Mopify opened on the queue list for a few hours now, but Chrome still shows me the same memory consumption as when I started (around 170 MB). 

Can you check if the memory leak is only happening in FireFox?

**Comment by JarnoNijboer** [comment]
I've tested it with chrome and firefox this afternoon and it occurs when starting a new station from a spotify playlist.

**Comment by dirkgroenen** [comment]
Oké, I will test and investigate that tomorrow.

**Comment by JarnoNijboer** [comment]
I can simulate this, by opening the queue in Mopify and add/remove track using the [MusicBox-Webclient] (https://github.com/woutervanwijk/Mopidy-MusicBox-Webclient)

**Comment by dirkgroenen** [comment]
Changing the queue in MusicBox's client makes Mopify leak?

**Comment by dirkgroenen** [comment]
A quick memory timeline test shows that creating a station doesn't leak memory. In the image I've started a station at the start and it ended adding tracks around 50000MS (where the line graph drops again). 

![http://i.imgur.com/9VVPSCB.png](http://i.imgur.com/9VVPSCB.png)
