### ISSUE TITLE
User playlists are not loaded properly

### ISSUE THREAD

**Issue by dblandin** [dirkgroenen/mopidy-mopify#63]
When I visit the following mopify URL `http://[ip address]/mopify/#/music/playlists`, I see two successful requests to `https://api.spotify.com/v1/me` followed by a malformed request for playlists: `https://api.spotify.com/v1/users/null/playlists?limit=50`.

What is displayed seems to be a default list of playlists that aren't in my account:

![screen shot 2015-02-25 at 3 58 52 pm](https://cloud.githubusercontent.com/assets/123595/6381534/60859a02-bd07-11e4-848e-274876128a49.png)

I can create a new playlist, but as soon as I refresh the page it disappears due to the bad load.

Any advice towards a fix or further troubleshooting?

**Comment by totokaka** [comment]
That looks like the play lists of a Norwegian user. Jobb -> work, middag -> dinner.

I can guess why you would the see the play lists of another user, though.

**Comment by dirkgroenen** [comment]
Null is a Spotift user, but in this it's your Spotify username that hasn't been loaded succesfully.

Which version are you running? This was a bug in a few versions back, but was solved.

**Comment by dirkgroenen** [comment]
#24 is the issue I was just referring to. Can you try if any of the answers in that threat "solve" your problem?

**Comment by dblandin** [comment]
Not sure. Whatever is currently available via PIP. Should I use a different installation method?

**Comment by dblandin** [comment]
Ahh, found it. Looks like I am a few versions behind.

**Comment by dblandin** [comment]
Never mind!

Had to upgrade mopify via PIP, reconnect with Spotify, and hard refresh the interface to get the right playlists to show up.

:+1:

**Comment by dirkgroenen** [comment]
Might need to improve the "update available" notification? Mopify is under heavy development, which means theirs a new version (with bug fixes and new features) almost every week.
