### ISSUE TITLE
mopify-sync appears in Mopidy's list of web clients

### ISSUE THREAD

**Issue by kingosticks** [dirkgroenen/mopidy-mopify#68]
This isn't a big deal, but rather than have a separate static and app (and have the sync app appear in Mopidy's list of web clients at http://localhost:6680/mopidy/) is it neater if you have just the app and swap your `RootRequestHandler` for a `mopidy.http.hander.StaticFileHandler` ? I've not tried this but maybe something like the following would work?
```
(r'/(.*)', mopidy.http.handers.StaticFileHandler, {'path': os.path.join(os.path.dirname(__file__), 'static')})
```

**Comment by dirkgroenen** [comment]
Already on my list for the next version. Since I'm new in Python I was already very happy to achieve this ;)

**Comment by kingosticks** [comment]
Awesome, thanks!

**Comment by dirkgroenen** [comment]
The two extensions are now (1.3.2) merged into one extension.
