### ISSUE TITLE
Master mode

### ISSUE THREAD

**Issue by jwiemann** [dirkgroenen/mopidy-mopify#71]
Is it possible to force all clients to use the spotify account from mopidy or a different config file? This would make it easier for new clients to join.

**Comment by dirkgroenen** [comment]
As you can read in #23 it wasn't possible to use credentials out of a config file. The synchronization service is the only way to make it possible to let multiple clients use the same Spotify credentials.

At the moment there isn't a forces master/slave mode. Everybody has the right to overrule the saved credentials, but when someone enabled the service for the first time it will use the credentials already stored in the sync service. 

I might add a master/slave mode in the future. The current sync service already [saves a list](https://github.com/dirkgroenen/mopidy-mopify/blob/master/mopidy_mopify/sync.py#L146-L149) of all connected clients with a master/slave property, but I haven't integrated it yet.

**Comment by halloalexkern** [comment]
Would this feature also allow to have auto-enabled-sync for new clients?
e.g. if a new clients logs in the first time, the sync-service (all GETs are fired) and spotify-service is already activated.
That would be awesome! btw.: great work!!

**Comment by dirkgroenen** [comment]
That is definitely possible. I'll keep it in mind when further developing the Sync service.

**Comment by dirkgroenen** [comment]
Will be available in the next release (1.5.0)
