### ISSUE TITLE
Unresponsive UI - can't play songs or start radio stations

### ISSUE THREAD

**Issue by antisoma** [dirkgroenen/mopidy-mopify#72]
The UI becomes unresponsive as it relates to the playing of songs or starting radio stations.  It is still possible to browse "Featured Playlists", "New Releases", "Playlists", etc.  So the unresponsiveness relates only to "Play Track", Add Track to queue", "Start Stations", etc.

This is on a Raspberry Pi 2.

Pastebins of mopidy.log:
http://pastebin.com/dpVtq5nx - just caught an example of it this morning
http://pastebin.com/xyRsskvp - longer log that may be helpful.

Happy to provide any additional information.  Also, thanks very much for this project, love it.

**Comment by dirkgroenen** [comment]
```
2015-02-27 22:00:47,278 WARNING [3919:MainThread] mopidy.__main__:   spotify/username must be set.
2015-02-27 22:00:47,278 WARNING [3919:MainThread] mopidy.__main__:   spotify/password must be set.
```

Looks like you haven't filled in your Spotify credentials in mopidy's config file?

**Comment by antisoma** [comment]
I believe that error was on the first run of mopidy.  Credentials were subsequently entered.  It no longer throws up that error.

**Comment by dirkgroenen** [comment]
So you can play songs from Spotify's library? For example your own playlists or a searched track?

If the search doesn't return any results it could be possible that your Mopidy is somehow not connecting with Spotify.

**Comment by antisoma** [comment]
Yes, I it is possible to play tracks from spotify.  But after some time the UI stops responding to these requests, ultimately requiring a reboot.

**Comment by dirkgroenen** [comment]
Does Mopify generates any errors at that point? I've noticed that Mopify sometimes stops responding to the Raspberry, but a refresh of the client solves that problem. When you say reboot you're mentioning at rebooting Mopidy right?

**Comment by antisoma** [comment]
I've not seen any errors.  I'm not clear where mopify would generate errors?  Is there a specific log?

Either restarting mopidy service ("sudo service mopidy restart"), or rebooting the device solves the problem.

**Comment by dirkgroenen** [comment]
Mopify generates errors in your browser's console. (Although you just gave me the idea to create a feature which saves all errors in a file on the Mopidy server.)

**Comment by antisoma** [comment]
Thanks.

If I encounter the problem tonight when at home I will check the console and post here.  I'll be more careful to detail the exact steps too.

Just to add that refreshing the client/browser does not help.

**Comment by antisoma** [comment]
I'm not at all fluent with console - so bear with me.

Trying to play a track from "Your music - songs":

 TypeError: Cannot read property '2' of undefined
    at mopidy-mopify-1.3.1.js:40490
    at i (mopidy-mopify-1.3.1.js:13200)
    at mopidy-mopify-1.3.1.js:13216
    at l.$eval (mopidy-mopify-1.3.1.js:14412)
    at l.$digest (mopidy-mopify-1.3.1.js:14228)
    at mopidy-mopify-1.3.1.js:14451
    at g (mopidy-mopify-1.3.1.js:4916)
    at mopidy-mopify-1.3.1.js:5296

Trying to start a station from "Albums":

http://i62.tinypic.com/ei5edw.png

Helpful?

**Comment by dirkgroenen** [comment]
Must say that I've never seen that error before. Does it happen with any track in your song collection?

**Comment by antisoma** [comment]
No, not always but often problems from "songs" view and with starting stations.  Here is a different error attempting to play a song (from "song") view, this is through the right-click context menu selecting "Play Track".  Double clicking to play a track is more reliable.

Unexpected response received. Message was: Object {jsonrpc: "2.0", id: 688, result: null}
mopidy-mopify-1.3.1.js:72921 WebSocket connection to 'ws://192.168.1.11:6680/mopidy/ws' failed: Invalid frame header
mopidy-mopify-1.3.1.js:74020 WebSocket error: Event {clipboardData: undefined, path: NodeList[0], cancelBubble: false, returnValue: true, srcElement: WebSocket…}
mopidy-mopify-1.3.1.js:74020 Potentially unhandled rejection [2] Error
    at Object.21.../lib/websocket/ (http://192.168.1.11:6680/mopify/assets/mopidy-mopify-1.3.1.js:32:29569)
    at e (http://192.168.1.11:6680/mopify/assets/mopidy-mopify-1.3.1.js:32:7702)
    at b (http://192.168.1.11:6680/mopify/assets/mopidy-mopify-1.3.1.js:32:7869)
    at http://192.168.1.11:6680/mopify/assets/mopidy-mopify-1.3.1.js:32:7886
    at http://192.168.1.11:6680/mopify/assets/mopidy-mopify-1.3.1.js:32:7454
    at http://192.168.1.11:6680/mopify/assets/mopidy-mopify-1.3.1.js:32:7459
mopidy-mopify-1.3.1.js:74020 Potentially unhandled rejection [4] Error
    at Object.21.../lib/websocket/ (http://192.168.1.11:6680/mopify/assets/mopidy-mopify-1.3.1.js:32:29569)
    at e (http://192.168.1.11:6680/mopify/assets/mopidy-mopify-1.3.1.js:32:7702)
    at b (http://192.168.1.11:6680/mopify/assets/mopidy-mopify-1.3.1.js:32:7869)
    at http://192.168.1.11:6680/mopify/assets/mopidy-mopify-1.3.1.js:32:7886
    at http://192.168.1.11:6680/mopify/assets/mopidy-mopify-1.3.1.js:32:7454
    at http://192.168.1.11:6680/mopify/assets/mopidy-mopify-1.3.1.js:32:7459

I also get "No Connection - Mopidy" in the song name - artist in the play bar occasionally.  I'm starting to wonder if I should try a fresh install of rasbian, mopidy and mopify.

**Comment by antisoma** [comment]
Also, I get this error often:

    Unexpected response received. Message was: Object {jsonrpc: "2.0", id: 294, result: null}

And this (not expanded):

    Unexpected response received. Message was: Object {jsonrpc: "2.0", id: 361, result: Array[10]}

**Comment by dirkgroenen** [comment]
The problem with the current song collection is that it isn't loaded through Mopidy, but via the Spotify service. As you can read in  #62 it takes a lot of power from your computer when you have a "big" song collection. 

I'm afraid that you don't have enough power 
Since you're running Mopidy on a Raspberry. At the moment I'm waiting at Mopidy's new version which should include a more reliable way of looking up tracks.

Mopify showing an Application Error in the console is just simply Mopidy which stopped working. Same goes for the No connection message in the seekbar.

**Comment by antisoma** [comment]
Interesting.  I've looked at CPU usage on the Pi 2 with "top" previously and it didn't give me any concerns.  I will look again when doing the actions that seem to cause the problems.

Probably a dumb question but is there a way to make it degrade gracefully on less powerful devices, either through code magic, partial loading of the songs list, or perhaps even an option to remove the "songs" list completely (I'm sure my family can live with albums, playlist, browse, and search).

The problem of course is that mopidy and mopify offer a degree of spotify integration that is not available anywhere else.  You've made it too good for me to want to use another option!

**Comment by antisoma** [comment]
Some investigation tonight:

Mopidy running for several hours but not being used to play music.

Actions and CPU usage:
Just playing song no other activity mopidy process CPU usage usually <%10
Starting station from song view maximum 60%
Starting station from album view maximum 60%
Listing songs view maximum maximum 114% but usually under 30%

Trying to play a song from song list (right click play track) - failed, no console error, no increase in CPU usage, then refresh browser fail.

Mopidy error:

 ```
2015-03-04 18:51:02,522 INFO [2046:SpotifyBackend-5] mopidy_spotify.playback: Playback of spotify:track:1pIYS6Jw0p5FQ1uljgcoMg failed: The track cannot be played
2015-03-04 18:51:02,538 WARNING [2046:Core-8] mopidy.core.tracklist: Track is not playable: spotify:track:1pIYS6Jw0p5FQ1uljgcoMg
2015-03-04 18:51:02,555 INFO [2046:SpotifyBackend-5] mopidy_spotify.playback: Playback of spotify:track:6nHYUs7hjOBPn3pznOntFS failed: The track cannot be played
2015-03-04 18:51:02,575 WARNING [2046:Core-8] mopidy.core.tracklist: Track is not playable: spotify:track:6nHYUs7hjOBPn3pznOntFS
```

Mopify not responsive, mopidy service is still running.  Restart mopidy service, restarting the service takes longer than normal (20 seconds compared to normally a few seconds)

Repeat some actions:
List song view - CPU <10%
Right click play track fails - CPU <10%, console error:

```
TypeError: Cannot read property '209' of undefined
    at mopidy-mopify-1.3.1.js:40490
    at i (mopidy-mopify-1.3.1.js:13200)
    at mopidy-mopify-1.3.1.js:13216
    at l.$get.l.$eval (mopidy-mopify-1.3.1.js:14412)
    at l.$get.l.$digest (mopidy-mopify-1.3.1.js:14228)
    at mopidy-mopify-1.3.1.js:14451
    at g (mopidy-mopify-1.3.1.js:4916)
    at mopidy-mopify-1.3.1.js:5296
```

Numerous other actions fail (but note that using mopify to browse, list playlists, albums etc works as normal), attempting to play station from albums fails returns in console:

   ``` 
TypeError: Cannot read property '232' of undefined
    at mopidy-mopify-1.3.1.js:40490
    at i (mopidy-mopify-1.3.1.js:13200)
    at mopidy-mopify-1.3.1.js:13216
    at l.$get.l.$eval (mopidy-mopify-1.3.1.js:14412)
    at l.$get.l.$digest (mopidy-mopify-1.3.1.js:14228)
    at mopidy-mopify-1.3.1.js:14451
    at g (mopidy-mopify-1.3.1.js:4916)
    at mopidy-mopify-1.3.1.js:5296
mopidy-mopify-1.3.1.js:74020 Unexpected response received. Message was:
```

Eventually a station from album view starts - minimal CPU use, no error returned.

Playing station from play list view, console error (again, minimal CPU usage):

     ```
Unexpected response received. Message was: Object {jsonrpc: "2.0", id: 259, result: null}
mopidy-mopify-1.3.1.js:74020 Server returned error: Object {message: "Application error", code: 0, data: Object}
```

**Comment by dirkgroenen** [comment]
Thanks for the detailed error log! At the moment I don't have time to further develop on Mopify, so I'll get back on this within the next few weeks!

**Comment by dirkgroenen** [comment]
This issue looks like to be the same as #62. Closing this one.
