### ISSUE TITLE
On demand loading of big playlists don't work with big windows

### ISSUE THREAD

**Issue by hoschi** [dirkgroenen/mopidy-mopify#76]
When starting with a big browser window there is no scrollbar and on demand loading is not triggered:
![big window, no scrollbar](https://cloud.githubusercontent.com/assets/163128/6542188/4eb35b64-c4f2-11e4-88ce-4bc95bffac6a.png)

When I resize the window to get a scrollbar, on demand loading starts as I scroll down.
![smaller window, scrollbar there, on demand loading gets triggered](https://cloud.githubusercontent.com/assets/163128/6542193/5bd9832c-c4f2-11e4-9b94-3dac8e7d87b0.png)

Browser is Chrome. Window is ~1440px high.

**Comment by dirkgroenen** [comment]
Ah I see, will fix it in the next version!

**Comment by dirkgroenen** [comment]
Should be fixed in V1.3.2, can you confirm?

**Comment by hoschi** [comment]
I flagged the AUR package "out of date" and wait for the new version.

**Comment by dirkgroenen** [comment]
Ok. The AUR package isn't maintained by me, so I can't tell you when it will be updated.

**Comment by hoschi** [comment]
I installed the updated package today and it works now :)

**Comment by dirkgroenen** [comment]
Great :)
