### ISSUE TITLE
cross platform synchronized play

### ISSUE THREAD

**Issue by vdbee** [dirkgroenen/mopidy-mopify#78]
Mopify already provided a kind of account sharing over a network. Would it be possible to extend that such that synchronized play over multiple instances of mopidy becomes possible?

**Comment by dirkgroenen** [comment]
I don't think it's something which should be implemented in Mopify since it is more of a backend feature, but I might explore the possibilities for creating a new plugin which does this. For now I'll close this issue since it's not relevant for Mopify.

**Comment by vdbee** [comment]
Ah, I see, so I should address this to mopidy?

**Comment by dirkgroenen** [comment]
A quick search in google brought me to a topic where one of the developers said that they still want to implement the sync feature. The topic was from august 2014 so I don't know what their ideas about this are now.

You could open an issue in the Mopidy repo and ask them.
