### ISSUE TITLE
Cannot install Mopify

### ISSUE THREAD

**Issue by NicoHood** [dirkgroenen/mopidy-mopify#8]
Hello!
I tried the Alpha (not the v1.0) and i have problems to install the extension. On a new Raspbian Wheezy with a B+

With a manual install i get
```
$ sudo python setup.py install
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools
```

And with the default installation methode i get
```
pip install Mopidy-Mopify
-bash: pip: command not found
```

I dont know in what package pip is located or how to get it.

**Comment by greg12579** [comment]
Just an FYI. I just encountered this 404 issue. 
Initially I used the default command on the github readme page to install.
"python3 -m pip install mopidy-mopify" 
Doing this gave the 404.
If I installed from the master zip, it worked. Hope this helps someone. Command below. 

sudo pip3 install https://github.com/dirkgroenen/mopidy-mopify/archive/master.zip

**Comment by hjek** [comment]
> And http://raspberrypi:6680/mopify/ gives a 404 error.

@NicoHood, You've made a typo. Try http://raspberrypi:6680/mopidy/
