### ISSUE TITLE
Update for Mopidy 1.0 compatability

### ISSUE THREAD

**Issue by kingosticks** [dirkgroenen/mopidy-mopify#81]
Not sure if this is on your radar but in Mopidy 1.0, [`PlaybackController.stop`](https://docs.mopidy.com/en/v1.0.0/api/core/#mopidy.core.PlaybackController.stop) no longer takes any arguments. When trying to play tracks with this latest version of Mopidy I get the following errors in the console:
> stop() got an unexpected keyword argument 'clear_current_track'

**Comment by dirkgroenen** [comment]
Thanks for the update, didn't know they already released 1.0. I'll check the changes and update Mopify asap.

**Comment by dirkgroenen** [comment]
Fixed for next release ([1.4.0](https://github.com/dirkgroenen/mopidy-mopify/milestones/1.4.0))
