### ISSUE TITLE
Problem with cgPrompt in development

### ISSUE THREAD

**Issue by werkshy** [dirkgroenen/mopidy-mopify#83]
I'm trying to get the development environment up and running. 

- OS X 10.10, node/npm from brew.
- Ran the instructions in README to get up and running in development
- Had to choose Angular version during bower install (choose 1.3.15)
    - One of the choices was `angular#~1.2.16 which resolved to 1.2.28 and is required by angular-prompt#1.1.0`.
    - All other choices/requirements were for 1.3.x

At this point, `grunt watch` gets the server up and running but I get this error in the browser.

<pre>
Error: [$injector:modulerr] Failed to instantiate module mopify due to:
[$injector:modulerr] Failed to instantiate module mopify.music.playlists due to:
[$injector:modulerr] Failed to instantiate module cgPrompt due to:
[$injector:nomod] Module 'cgPrompt' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.3.15/$injector/nomod?p0=cgPrompt
minErr/<@http://localhost:8000/src/vendor/angular/angular.js:63:12
module/<@http://localhost:8000/src/vendor/angular/angular.js:1774:1
ensure@http://localhost:8000/src/vendor/angular/angular.js:1698:38
module@http://localhost:8000/src/vendor/angular/angular.js:1772:1
loadModules/<@http://localhost:8000/src/vendor/angular/angular.js:4115:22
forEach@http://localhost:8000/src/vendor/angular/angular.js:323:11
loadModules@http://localhost:8000/src/vendor/angular/angular.js:4099:5
loadModules/<@http://localhost:800
</pre>

I am unfamiliar with bower, sorry if this is a dumb question.

**Comment by werkshy** [comment]
Ah, figured it out. Pull request to follow.

**Comment by dirkgroenen** [comment]
Fixed in next release. Turned out that the angular-prompt was missing in the .gitignore.
