### ISSUE TITLE
Can't seem to play music without using the shuffle playlist button.

### ISSUE THREAD

**Issue by Delanoman** [dirkgroenen/mopidy-mopify#86]
Directly clicking on music to play it doesn't seem to work. 
Already ran Mopidy with the -v option, but it never gives any error messages. 
Is this a current known bug? Or should i somehow provide more info?

EDIT: I noticed almost the same behaviour within other Mopidy webclients.

Using a Raspberry Pi 2 with latest Rasbian OS.
Tested on a iPhone 6 Safari/Chrome and on a Mac Safari/Chrome.

P.S I love the design!

**Comment by dirkgroenen** [comment]
Can you provide a bit more information on what happens with the client? Does it throw errors in the browser's console (Developer tools)?  

I have seen this problem a few times at the office. Every time it happened it showed 'No connection' in the player. Does this also happen when you try to start the songs?

**Comment by Delanoman** [comment]
Yes it throws errors in the developer console. It does say 'No connection' when selecting only one song. When pressing 'Shuffle Playlist', it all works fine.

mopidy-mopify-1.3.2.js:73883 Server returned error: Object {message: "Invalid params", code: -32602, data: Object}code: -32602data: Objectmessage: "stop() got an unexpected keyword argument 'clear_current_track'"traceback: "Traceback (most recent call last):↵  File "/usr/local/lib/python2.7/dist-packages/mopidy/utils/jsonrpc.py", line 132, in _handle_single_request↵    result = self._unwrap_result(result)↵  File "/usr/local/lib/python2.7/dist-packages/mopidy/utils/jsonrpc.py", line 221, in _unwrap_result↵    result = result.get()↵  File "/usr/local/lib/python2.7/dist-packages/pykka/future.py", line 299, in get↵    exec('raise exc_info[0], exc_info[1], exc_info[2]')↵  File "/usr/local/lib/python2.7/dist-packages/pykka/actor.py", line 200, in _actor_loop↵    response = self._handle_receive(message)↵  File "/usr/local/lib/python2.7/dist-packages/pykka/actor.py", line 294, in _handle_receive↵    return callee(*message['args'], **message['kwargs'])↵TypeError: stop() got an unexpected keyword argument 'clear_current_track'↵"type: "TypeError"__proto__: Objectmessage: "Invalid params"__proto__: Object
2015-04-05 15:31:47.646mopidy-mopify-1.3.2.js:73883 Potentially unhandled rejection [5] Error
    at Object.21.../lib/websocket/ (http://192.168.1.215:6680/mopify/assets/mopidy-mopify-1.3.2.js:32:28960)
    at e (http://192.168.1.215:6680/mopify/assets/mopidy-mopify-1.3.2.js:32:6935)
    at b (http://192.168.1.215:6680/mopify/assets/mopidy-mopify-1.3.2.js:32:7102)
    at http://192.168.1.215:6680/mopify/assets/mopidy-mopify-1.3.2.js:32:7119
    at http://192.168.1.215:6680/mopify/assets/mopidy-mopify-1.3.2.js:32:6687
    at http://192.168.1.215:6680/mopify/assets/mopidy-mopify-1.3.2.js:32:6692mopidy-mopify-1.3.2.js:73883 (anonymous function)mopidy-mopify-1.3.2.js:73883 dmopidy-mopify-1.3.2.js:73883 j
![schermafbeelding 2015-04-05 om 15 32 31](https://cloud.githubusercontent.com/assets/3406510/6996996/1fdadbf0-dba9-11e4-8e29-1ea47bbf8b7e.png)

**Comment by dirkgroenen** [comment]
Are you using Mopidy 1.0.0? If so than Mopidy isn't compatible at the moment. I hope to release version 1.4.0, which is compatible with 1.0.0, today.

**Comment by Delanoman** [comment]
Ahh, yes I use Mopidy version 1.0.0. Do you recommend to downgrade mopidy for now? Or wait till next version? If yes, what Mopidy version is officially supported?

**Comment by dirkgroenen** [comment]
I've finished the last issues and are currently testing 1.4.0. If everything works it should be online somewhere in the next hour(s). 

At the moment 0.19 is the last official supported Mopidy.

**Comment by Delanoman** [comment]
Okay, so it isn't worth it downgrading to 0.19 now. I'll wait patiently! 
Thank you! / Enorm bedankt ;)

**Comment by dirkgroenen** [comment]
I have just released 1.4.1 and uploaded it. This should fix your problems. ;)

**Comment by Delanoman** [comment]
Unfortunately I ran into a similar error. Now it sometimes works, but when I sometimes select a song (double click, is that wanted behavior?) it won't play it.

Also the volume selector seems to be unresponsive most of the time, only after adjusting the volume level several times it will change the real volume.

![schermafbeelding 2015-04-05 om 17 02 59](https://cloud.githubusercontent.com/assets/3406510/6997258/dd56273c-dbb5-11e4-8399-b679efa05209.png)

**Comment by dirkgroenen** [comment]
Hmm that sucks. I will further invest the problem, but tonight we have to drink some beers and celebrate Easter Day ;)

**Comment by Delanoman** [comment]
Looking forward to it! Cheers!

**Comment by dirkgroenen** [comment]
Oh btw, can you enable debug mode in your config file and repost the error when it occurs? This will load the unminified version of Mopify which makes it a bit easier for me to identify the location of the problem. 

You can enable it by adding the following line(s) in your config file:

```
[mopify]
enable = true
debug = true     # this line can be added as of 1.4.1
```

**Comment by dirkgroenen** [comment]
I think I've already found the problem causing these errors. I've changed the code in the development branch and will merge it somewhere in the next few days.

**Comment by Delanoman** [comment]
Again I'll wait patiently! 
Thank you!

**Comment by dirkgroenen** [comment]
Just releases 1.4.2 which should fix this.

**Comment by Delanoman** [comment]
It seems like it is fixed! Thanks!

**Comment by dirkgroenen** [comment]
Great!
