### ISSUE TITLE
Improve automatic updating

### ISSUE THREAD

**Issue by dirkgroenen** [dirkgroenen/mopidy-mopify#87]
With release 1.4.1 I've added a beta version of automatic updating. Somewhere in the next releases I want to polish this feature and add an option which enables full automatic updating when a new version has been released. Could also move the auto-updating feature to it's own service...

In the mean time this thread can be used to improve this feature, drop ideas and mention issues in the current version.

**Comment by kingosticks** [comment]
https://github.com/mopidy/mopidy/issues/502 is probably relevant

**Comment by kingosticks** [comment]
What happens when the updated version requires additional or updated dependencies? E.g. When it requires a newer version of mopidy? In some cases you might not want this as it may break compatability with other extensions.

**Comment by dirkgroenen** [comment]
It will run the default pip upgrade command, which will update dependencies when needed. I can understand that some people don't want this, that's why the feature has been added as an option which can be enabled/disabled on the settings page.

**Comment by kingosticks** [comment]
Oh excellent. As long as it can be disabled that's fantastic. Cheers.

**Comment by dirkgroenen** [comment]
Jup, it's off be default and can be enabled through the settings page. 

![](http://i.imgur.com/MMISrZ5.png)
