### ISSUE TITLE
Fetching playlists doesn't seem to work

### ISSUE THREAD

**Issue by jaedb** [dirkgroenen/mopidy-mopify#9]
Firstly, very, very cool new UX design. My project was humming along, but I can see you've been hard at work making yours even better, so I think I'll give yours another go.

However, when attempting to view 'My Playlists', I see a `playlists not defined` error, and no playlists are loaded into the DOM. I've attached a screenshot below:

![Playlists not defined](https://cloud.githubusercontent.com/assets/1711444/5604781/8d7a6d4c-9437-11e4-8a6c-620c8eed4285.png)

**Comment by jaedb** [comment]
PS. You'll have to forgive low-res screenshot, I'm working on a small laptop. The main UX content panel doesn't load any playlists or content at all, and doesn't display any errors.

**Comment by dirkgroenen** [comment]
Thanks for trying the new mopify out! 

I've just opened it in Chrome and Firefox, but I can't simulate your error. When I'm connected to Spotify I get my spotify playlists and when I'm not I'm getting the playlists from Mopidy. 

I'll try to dig a bit deeper in to it, in the mean time I'm creating a source map file for the .js file which will be included in version 1.0.1. Hopefully that will make it a bit easier to find out where the error occurs.

**Comment by dirkgroenen** [comment]
Should be fixed now. Uploading the new version to pypi within a few minutes.
