### ISSUE TITLE
Mobile UI

### ISSUE THREAD

**Issue by hkultraman** [dirkgroenen/mopidy-mopify#90]
Hi,

Just want to check can I force to use mobile ui? Currently, even I am using my android chrome to access mopify, it shows me a desktop version of ui. Is there anyway I can force to access a mobile version of mopify?

Many thanks.

**Comment by dirkgroenen** [comment]
The mobile version is nothing more than a responsive design on the desktop interface. Based on your screen's resolution you should get the mobile layout.

Which phone do you have?

**Comment by hkultraman** [comment]
Hi, thx for your reply. Actually, I have 2 phones 

1. Samsung Galaxy S5 LTE-A res: 2560 x 1440
2. LG GK res: 1920 x 1080

Trying with both phones to mopify. Both shows me a desktop version.

**Comment by dirkgroenen** [comment]
The Galaxy S5 has a pixel ratio of 3.0, which brings the resolution back to 360x640. The resolution should definitely show the mobile layout. Can you make a print screen of your screen and post it? I'm quite wondering how the interface looks on your telephone.

**Comment by hkultraman** [comment]
![screenshot_2015-04-19-18-28-42](https://cloud.githubusercontent.com/assets/7135751/7219094/1c336020-e6c2-11e4-9504-630b26ce8815.png)
![screenshot_2015-04-19-18-28-03](https://cloud.githubusercontent.com/assets/7135751/7219095/2741882a-e6c2-11e4-9e38-a278224ecb70.png)

**Comment by hkultraman** [comment]
Pls see my above comment

**Comment by dirkgroenen** [comment]
To be honest, I dont know why that is happening. Everything works perfectly when testing it on my Galaxy S5 and Browserstack. Have you tried an other browser?

**Comment by hkultraman** [comment]
BTW, I am using the version come with pi-music box v 0.6.  Don't know is it the cause.

**Comment by dirkgroenen** [comment]
Which Mopify version are you using? You can check that on the settings page.

**Comment by hkultraman** [comment]
Checked, it is 1.12

**Comment by dirkgroenen** [comment]
I assume you refer to 1.1.2? In that case you could have read on in the changelog that responsive support has been added since version 1.2.0. Update your client to at least 1.2.0 and you will be able to use the responsive design.

**Comment by hkultraman** [comment]
Thx for solving my issue.

As I know that start from 1.4.1 which drops the support of mopidy < 1.0

However, the version of mopidy come with pi-music box is 0.19.5.

Is it possible to use the following command upgrade to 1.4.0 instead of latest?

sudo pip install --upgrade Mopidy-Mopify

Sorry for my dump question.

Many thx.

**Comment by dirkgroenen** [comment]
For as far as I know PiMusicbox has it's own web interface? Installing a specific version with PIP can be done using the following command:

```bash
pip uninstall Mopidy-Mopify
pip install Mopidy-Mopify==[preferred-version]
```

**Comment by hkultraman** [comment]
Thx dirkgroenen, end up I can update my mopify to 1.3.2. And note I can enjoy the mobile edition UI.Thx

**Comment by hkultraman** [comment]
Further to my last comment, I have updated my pi-musicbox v0.6 with mopidy 1.0.0 and mopify 1.4.2. 

Thanks @dirkgroenen once. The responsive UI is quite good indeed.

BTW, I find that the simple web client from pi-musicbox come with "System->Shutdown" and "System->Restart" UI. Will you consider to add these 2 features to mopify as well?

Many thanks.

**Comment by dirkgroenen** [comment]
Still thinking about a service which adds system controls (like shutdown and restart). This may get handy in combination with Automatic Updating ( #87 ). You can create an other issue for this idea. That way  other people can share their opinion about it and it would remind me.

**Comment by hkultraman** [comment]
BTW, seems using Mobile UI can't adjust system volume, isn't  it?

thanks

**Comment by hkultraman** [comment]
@dirkgroenen seems using Mobile UI can't adjust system volume, isn't it?

thanks

**Comment by dirkgroenen** [comment]
Correct, still need to integrate that.

**Comment by hkultraman** [comment]
@dirkgroenen seems like on mobile ui, on artist page, no link to its biography and related artists, isn't it.

**Comment by dirkgroenen** [comment]
Correct
