### ISSUE TITLE
"Use Spotify as playlist source" disabled when enabling sync

### ISSUE THREAD

**Issue by mattb18** [dirkgroenen/mopidy-mopify#91]
When enabling Sync services the Spotify option "Use Spotify as playlist source"  is disabled by default. This means enabling it on each new browser. If I enable Sync services on mobile this option is enabled by default. 

Thanks

**Comment by dirkgroenen** [comment]
I can't replicate this. Are you sure you haven't enabled it before on your mobile?

**Comment by mattb18** [comment]
Yeah it's the first time I have accessed it on my phone. It has been disabled by default on both OSX and Windows in browsers Firefox, Chrome and IE.

I have since tried it on another phone and it was also enabled.

**Comment by dirkgroenen** [comment]
Hmm, I've never seen this happening before. I will keep an eye on it and try to find the reason why it's happening.

**Comment by mattb18** [comment]
This appears to have been resolved since the Master Sync feature has been added. Thanks!

**Comment by dirkgroenen** [comment]
Great! In that case I'll close this one. Let me know if it comes back.
