### ISSUE TITLE
[V2.0] Create a 'product brand' around Mopify and possibly rename it

### ISSUE THREAD

**Issue by dirkgroenen** [dirkgroenen/mopidy-mopify#94]
Mopify was the first thing I could think of when I started the project a few years ago. Since Mopify is growing and more people should recognize the client on the internet it would be good to change it's name and create a little brand around it (logo, website etc.).

If anyone has a cool idea, let me know!

**Comment by dirkgroenen** [comment]
Let's write it down: `sonate`

**Comment by kingosticks** [comment]
It's very similar to [sonata MPD client](http://sourceforge.net/projects/sonata.berlios/).

**Comment by dirkgroenen** [comment]
Hmm, that kills that idea.. Let's keep on brainstorming than.

**Comment by kingosticks** [comment]
Mopicl[iy]?

**Comment by dirkgroenen** [comment]
Kinda wanna get rid of the name association with Mopidy. I can always make the decision to add Mopidy as a prefix in certain expressions.

**Comment by BLX-S** [comment]
Just shouting some stuff out, Plyphony, Rookd, WeaveStream. This also depends if you want to branch this project out into a total independent thing. That would be super cool. You could launch a site and provide ready to flash images for Raspberry Pi (which is where most people run MPD nowadays). I don't know if it would help for branding to create a simple Phonegap clone of the Mobile WebUI. That way you can "market" the apps.

Currently I'm running Mopify on a Raspberry Pi with Pi MusicBox and my idea was to position mopify as a distro for spotify streaming...
