### ISSUE TITLE
Add Link to Artist Biography and Related Artists on Mobile UI

### ISSUE THREAD

**Issue by hkultraman** [dirkgroenen/mopidy-mopify#95]
Please, add Link to Artist Biography and Related Artists on Mobile UI.

Many thanks.

https://github.com/dirkgroenen/mopidy-mopify/issues/90#issuecomment-96175920

**Comment by dirkgroenen** [comment]
I'm still considering to completely redesign the artists page. Until I've decided this I won't make any changes to the page. 

In case I am going to redesign the page, a Biograpy and related artists section will definitely be available in the mobile interface.

**Comment by anil72749** [comment]
Find out which celebrity is blowing the birthday candles along with you today! Look for celebrity born today / famous people birthdays, bio & more at http://www.celebrityborn.com/
