### ISSUE TITLE
Context menu on Mobile UI

### ISSUE THREAD

**Issue by coda4k** [dirkgroenen/mopidy-mopify#97]
Hello! Is there any way to activate the context menu on the Mobile UI (iOS + Chrome)? It would be great to be able to add songs to queue or playlists.

Thanks in advance!

**Comment by dirkgroenen** [comment]
Yes, you can activate it bij holding down your finger on the screen.

**Comment by coda4k** [comment]
I've been trying to activate it that way but it seems it's not working for me neither on chrome nor on safari :(

**Comment by dirkgroenen** [comment]
Which context menu are you trying tot open? A track's or tile's?

**Comment by dirkgroenen** [comment]
Closed due inactivity.
