### ISSUE TITLE
WebApp Manifest

### ISSUE THREAD

**Issue by daxterng** [dirkgroenen/mopidy-mopify#98]
Is it possible to use Mopify as WebApp?

Would be very handy to use on a Smartphone.

http://www.w3.org/TR/appmanifest/

Shouldnt be to difficult or am I wrong?

**Comment by dirkgroenen** [comment]
Is already something on my to-do list, but I'm waiting for the moment where I come up with a new name/brand (#94) for Mopify so I can use the correct app icons.

**Comment by dirkgroenen** [comment]
Added in latest version.
